Problem (Fix #81): reward<->punishment<->monetary update interactions not explicitly stated
crypto-com/thaler-docs pull request #102
Opened 2020-03-13 08:05 UTC by yihuang

Solution:
- Add a doc to describe staking/validator state transitions.

2020-03-13 08:11 UTC, lezzokafka commented on docs/getting-started/punishments.md
> +validator for the firs evidence that we get from tendermint and ignore other evidences until `UNBONDING_PERIOD`).  :::
typo?

2020-03-13 08:15 UTC, tomtau commented on docs/getting-started/punishments.md
> +validator for the firs evidence that we get from tendermint and ignore other evidences until `UNBONDING_PERIOD`).  :::
firs -> first?

2020-03-13 08:16 UTC, yihuang commented on docs/getting-started/punishments.md
> +validator for the firs evidence that we get from tendermint and ignore other evidences until `UNBONDING_PERIOD`).  :::
Oh, sorry, the punishments are added by mistake, just removed it from the commit.

2020-03-13 08:46 UTC, tomtau requested changes
looks good for a start

2020-03-13 08:46 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
Why to keep `old_validator_keys` in here?

2020-03-13 08:46 UTC, tomtau commented on docs/modules/staking-state.md
> +keys can't be re-used by other validators before cleaned up.
what about just blacklisting them (and the blacklist holds pub key / tm address->staking address mapping)? that would enforce the logical many (consensus pub key)-to-one (staking address) rather than many-to-many

2020-03-13 08:46 UTC, tomtau commented on docs/modules/staking-state.md
> +- `bonded >= min_required_staking`
so, there's no more "min_effective"? I guess that should then be removed from elsewhere in the docs?

2020-03-13 08:46 UTC, tomtau commented on docs/modules/staking-state.md
> +For example, if you are the `max_validators + 1`-th active validator, so you are not chosen yet, but if anyone in the
it'll be helpful to show this example more in detail altogether with the expected generated ValidatorUpdates

2020-03-13 08:46 UTC, tomtau commented on docs/modules/staking-state.md
> +struct Validator {
the slashing docs say that, for byzantine faults, it'll be slashed just once -- how will that be decided / checked that it happened, so that it doesn't get slashed? My guess is that it'll be based on `jailed_until.is_some()`, but I may be wrong -- in any case, it'll be good to explicitly state this "interaction"

2020-03-13 08:52 UTC, lezzokafka reviewed
Some comments:

2020-03-13 08:52 UTC, lezzokafka commented on docs/modules/staking-state.md
> +- `bonded >= min_required_staking`
Align with [EFFECTIVE_MIN_STAKE](https://crypto-com.github.io/getting-started/staking.html#effective-min-stake)?

2020-03-13 08:52 UTC, lezzokafka commented on docs/modules/staking-state.md
> +When `bonded < min_required_staking`, this transition happens.
Same as the  line 58 comment

2020-03-13 08:52 UTC, lezzokafka commented on docs/modules/staking-state.md
> +  > _**NOTE:**_ Slashings for different faults are considered independent operations, each slashing will increase nonce independently.
```suggestion
  > _**NOTE:**_ Slashings for different faults are considered to be independent operations, each slashing will increase nonce independently.
```

2020-03-13 08:52 UTC, lezzokafka commented on docs/modules/staking-state.md
> +When an inactive validator re-join, it can provide different validator key, but it still need to be hold responsible for
Just want to check if I understand it correctly: 
- Validator A usign validator key K_1 and Staking address A_1 to join the network.
- Then he leave the network. 
- He rejoin with validator key K_2 and Staking address A_1 to rejoin andit will be slash if byzantine fault was committed under K_1  and A_1?

2020-03-13 09:03 UTC, yihuang commented on docs/modules/staking-state.md
> +- `bonded >= min_required_staking`
Yes, if we agree on this version of logic.

2020-03-13 09:14 UTC, yihuang commented on docs/modules/staking-state.md
> +keys can't be re-used by other validators before cleaned up.
There is a many to one `tm address -> staking address` map for all the validators, and there is an invariant that this map should be consistent with staking merkle trie. So you can clean them up by lookup reversely with `old_validator_keys`, like:
```rust
for key in validator.old_validator_keys {
  tm_address_map.remove(key.address())
}
```
Also, since no evidence the validator key is compromised, no need to blacklist it? 
And there is no cleanup logic for the blacklist map yet, so better to keep it as small as possible.
I think it's the most balanced solution.

2020-03-13 09:23 UTC, yihuang commented on docs/modules/staking-state.md
> +struct Validator {
I add a simple description under the "Implications of jailing":

"Jailed validators won't be slashed again for byzantine faults."

2020-03-13 09:24 UTC, yihuang commented on docs/modules/staking-state.md
> +- `bonded >= min_required_staking`
Yeah, this is actually deviated from the current logic, there's no `EFFECTIVE_MIN_STAKE` in this one.

2020-03-13 09:27 UTC, yihuang commented on docs/modules/staking-state.md
> +When an inactive validator re-join, it can provide different validator key, but it still need to be hold responsible for
Yes, the evidence will include K_1, and we need to be able to connect it to A_1, and slash it.

2020-03-13 09:29 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
There is a many-to-one `tm address -> staking address` map, the `old_validator_keys` is like the reverse of it, so when cleanup, we can iterate `old_validator_keys` to cleanup that map.

2020-03-13 09:56 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
Any bounds on that? As this gets loaded in memory, one can blow this up cheaply by repeated node joins with an inactive or a borderline active (do repeated small amount unbond/deposit)

2020-03-13 10:02 UTC, yihuang commented on docs/modules/staking-state.md
> +For example, if you are the `max_validators + 1`-th active validator, so you are not chosen yet, but if anyone in the
Done

2020-03-13 10:05 UTC, tomtau commented on docs/modules/staking-state.md
> +keys can't be re-used by other validators before cleaned up.
For the blacklist, I assume it's on-disk key-value lookup and it won't take much space with index key compressions and other magic the db may do. For faster lookups, one may have a fixed size probabilistic filter and only check on-disk to exclude false positives.
--
with this dual handling, there's an extra complexity and one needs to be careful. 
I'm fine with it -- but extra clarification needed: https://github.com/crypto-com/chain-docs/pull/102#discussion_r392129384

2020-03-13 10:06 UTC, yihuang commented on docs/modules/staking-state.md
> +For example, if you are the `max_validators + 1`-th active validator, so you are not chosen yet, but if anyone in the
It's also trivial to switch to current logic by inactivating the validators who are not chosen into the top N at the end_block.

2020-03-13 10:15 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
Actually, with this version, the validator needs to unbond to bellow `min_required_staking` to inactivate itself.
So there is some opportunity cost to it, but it brings us to another problem which is no cheap way to just change the validator key?

2020-03-13 10:16 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
> Any bounds on that?
yeah, maybe the simplest solution is set a bound.

2020-03-13 10:42 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
there is an opportunity cost, but that assumes one joined in order to be a validator and care about the long term -- what if I joined simply for DoS -- this dynamic vector is a good target.

2020-03-13 10:48 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
> yeah, maybe the simplest solution is set a bound on that, when reached the bound, he's not allowed to use a new key again, but still allow to change to one of the old keys he owns?

possibly? or banning old keys altogether + some time limit on update frequency?

later, it'll be good to add some "update" tx -- either to update just the non-consensus metadata (name, security contact) or rotate the consensus pubkey -- it doesn't need to be in the immediate scope of this PR, but it's good to keep in mind how roughly that could work / if something like this could be added without introducing some attack vectors

2020-03-13 11:18 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
> possibly? or banning old keys altogether

With banning, I suppose we still need some way to clean the old stuff? Maybe recording a timestamp for now? `tm address -> (staking address, ban_time)`.

> + some time limit on update frequency?

What do you mean by this?

2020-03-13 11:24 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
> later, it'll be good to add some "update" tx -- either to update just the non-consensus metadata (name, security contact) or rotate the consensus pubkey -- it doesn't need to be in the immediate scope of this PR, but it's good to keep in mind how roughly that could work / if something like this could be added without introducing some attack vectors

If we will support cheaply rotate the consensus pubkey, then the banned key will increase rapidly even for a outer storage. Then I think storing it with `StakedState` with a maximum bound would be simpler.
We can store the timestamp with it:
```
Vec<(tm address, timespec)>
```
So we can clean up old ones(> max_evidence_age) as soon as possible.

2020-03-16 01:14 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
>  time limit on update frequency

e.g. once per day and only above the min required stake can do it

2020-03-16 01:23 UTC, tomtau requested changes
looks ok, but the example may have an error or needs a clarification

2020-03-16 01:23 UTC, tomtau commented on docs/modules/staking-state.md
> +  - addr3 -> 3
should here be also:
```
addr1 -> 0
addr4 -> 4
```

as 1 < 3 and 1 < 4?

(I don't know if the arrows in this example refer to vote power?)

2020-03-16 01:49 UTC, yihuang commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
> > time limit on update frequency
> 
> e.g. once per day and only above the min required stake can do it

You mean frequency to update validator key? If we have upper bound on the length of the used key list, then don't need a limit on frequency?

2020-03-16 01:53 UTC, yihuang commented on docs/modules/staking-state.md
> +  - addr3 -> 3
Yes, the right side of the arrow is the voting power, I should add some clarifications.

2020-03-16 01:58 UTC, yihuang commented on docs/modules/staking-state.md
> +  - addr3 -> 3
Done

2020-03-16 03:13 UTC, tomtau commented on docs/modules/staking-state.md
> +    old_validator_keys: Vec<TendermintValidatorPubKey>,
size upper bound (could be even compile-time constant) + cleaning works as well.

2020-03-16 03:15 UTC, merged