Problem: overlapping README and getting started (CRO-293)
crypto-com/thaler-docs pull request #11
Opened 2019-08-14 07:23 UTC by lezzokafka

Solution: Create tendermint_local_full_note.md

2019-08-15 01:51 UTC, tomtau requested changes
I think the "manual step" tutorial is quite good -- only a few small changes / typos.

Plus, since this is in a new file, have you tried generating the docs web?
I think we may need to link this new file from somewhere or put it in this configuration: https://github.com/crypto-com/chain-docs/blob/master/docs/.vuepress/config.js (@brianMCO can comment / help) 
Otherwise, it won't be included in the "rendered" docs.

2019-08-15 01:51 UTC, tomtau commented on docs/getting-started/tendermint_local_full_note.md
> +- Generate an stacking address for the wallet to receive genesis funds. You will be prompted to enter the wallet passphrase again to verify.
```suggestion
- Generate a staking address for the wallet to receive genesis funds. You will be prompted to enter the wallet passphrase again to verify.  
```

2019-08-15 01:51 UTC, tomtau commented on docs/getting-started/tendermint_local_full_note.md
> +<a id="wallet" />
Are these anchors needed? I think @calvinaco previously used them in README, because README has a manual "table of content" where it links these sections

2019-08-15 01:51 UTC, tomtau commented on docs/getting-started/tendermint_local_full_note.md
> +## Start a Local Full Node
Perhaps "Local Development Full Node" is more precise?

2019-08-15 01:59 UTC, lezzokafka commented on docs/getting-started/tendermint_local_full_note.md
> +- Generate an stacking address for the wallet to receive genesis funds. You will be prompted to enter the wallet passphrase again to verify.
Thanks Tom :3

2019-08-15 08:49 UTC, lezzokafka commented on docs/getting-started/tendermint_local_full_note.md
> +<a id="wallet" />
Removed unused [anchors](https://github.com/crypto-com/chain-docs/pull/11/commits/1e0b423f82bd6232b7e46ed3cbd953557204e6a2)

2019-08-15 08:53 UTC, lezzokafka commented on docs/getting-started/tendermint_local_full_note.md
> +## Start a Local Full Node
Updated [title](https://github.com/crypto-com/chain-docs/pull/11/commits/046d04288ad910bbf06bb8263af29ad9bc973630)

2019-08-16 03:13 UTC, tomtau requested changes

2019-08-16 03:13 UTC, tomtau commented on docs/.vuepress/config.js
> +        'local_full_node_development',
should it also be added to the PDF export sorter?

2019-08-16 06:26 UTC, lezzokafka commented on docs/.vuepress/config.js
> +        'local_full_node_development',
[Updated](https://github.com/crypto-com/chain-docs/pull/11/commits/a31c2e798847a6ca2f4718a2237b3e5746cc8e07). Tested with the pdf builder as well, no worries.

2019-08-16 07:04 UTC, tomtau approved these changes
lgtm

2019-08-16 07:05 UTC, merged