Problem (Fix#114): No technical glossary
crypto-com/thaler-docs pull request #122
Opened 2020-04-06 14:50 UTC by lezzokafka

**Solution**:
- Added technical glossary for ~40 technical jargons in `technical_glossary.md`, 
will keep adding as we go.

**Extra**:
- Fixed some broken links/typos in `node-joining.md ` and `staking-state.md`

2020-04-07 02:26 UTC, tomtau requested changes
looks good -- technical glossary was much needed!
left a few comments, as a few terms were a bit imprecise

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The Hierarchical Deterministic wallet is a system of deriving keys from a single starting point known as mnemonic phrase, which can be easily back up and restored.
the starting point is a seed -- mnemonic words are just a way to "serialise" the seed

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +A human-readable 24-word mnemonic phrase of a wallet. User can restore their wallet and associated addresses with it.
BIP39-compatible?

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The Hierarchical Deterministic wallet is a system of deriving keys from a single starting point known as mnemonic phrase, which can be easily back up and restored.
BIP32-compatible?

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The last two hex characters of the Chain ID. Using our testnet Chain ID `testnet-thaler-crypto-com-chain-42` as an example, the network ID would be `42`.
0x42 -- i.e. 66 in decimal.

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The validator who finalized the block.
not sure if "finalised" is the right word.
Also perhaps  -- it's a validator that was selected by https://docs.tendermint.com/master/spec/reactors/consensus/proposer-selection.html

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The Intel® Software Guard Extensions (SGX) is a set of instructions that increases the security of application code and data, giving them more protection from disclosure or modification.
it doesn't increase the security -- there could still be insecure applications.
It allows ensuring their integrity and confidentiality by isolating them from the OS or other enclaves

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The key pair for signing messages from the validator. The full key pair is located under the tendermint `priv_validator_key.json` folder.
That's in development.
In reality, the private key may not reside on the machine -- e.g. https://github.com/iqlusioninc/tmkms#hardware-security-modules-recommended

2020-04-07 02:26 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The key for viewing encrypted transactions.
key pair to enforce the access to confidential transaction data

2020-04-07 02:29 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
also length is 20 bytes

2020-04-07 02:30 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +A unique identifier for the blockchain. Different [prefixes](./chain-id-and-network-id.md#chain-id) of the Chain ID are used to distinguish between _devnet_, _testnet_ and _mainnet_.
it would useful to add full; predefined chain_ids for example

2020-04-07 02:31 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
I think that's implied by "follows the format" -- but it may be expanded, e.g. by referring to Eth docs where the address is specified?

2020-04-07 02:32 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
Sure thing 👍

2020-04-07 02:33 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +A unique identifier for the blockchain. Different [prefixes](./chain-id-and-network-id.md#chain-id) of the Chain ID are used to distinguish between _devnet_, _testnet_ and _mainnet_.
The link leads to https://crypto-com.github.io/getting-started/chain-id-and-network-id.html but it may be ok to repeat it

2020-04-07 02:34 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +The nonce is the number of transactions that have the witness of the staking address.
this is also crucial to  pervent tx replay attacks, because submitted txs are ordered by nonce.

2020-04-07 02:35 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +**tmkms**
tm kms?

2020-04-07 02:35 UTC, tomtau commented on docs/.vuepress/config.js
> +            "technical_glossary":21
I'm thinking whether this should be at the end -- perhaps its priority can be -1 or 0 to be the top?

In the interest of new pages, it may be also be good to put the priorities as multiples of 10 (10, 20, 30, 40...), so these editing reorderings are easier

2020-04-07 02:36 UTC, tomtau commented on docs/.vuepress/config.js
> +            "technical_glossary":21
(I guess the numerical ordering only affects PDF generation?)

2020-04-07 02:39 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +The address for payments/value transfers. Different prefixes of the transfer address are used to distinguish between devnet, testnet and mainnet.
in cro, transfer address are also roothash of multi-sig address, which is 32 bytes.
roothash of merkletree of m/n multisig pubey combination hashes.

2020-04-07 02:40 UTC, leejw51crypto approved these changes
lgtm

2020-04-07 02:41 UTC, leejw51crypto commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
ya, it's 20 cut of full pubkey in eth.

2020-04-07 02:42 UTC, lezzokafka commented on docs/.vuepress/config.js
> +            "technical_glossary":21
Yes, it is just the ordering. If you gen the pdf now, is like 139 pages...haha

2020-04-07 02:45 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The address for payments/value transfers. Different prefixes of the transfer address are used to distinguish between devnet, testnet and mainnet.
I guess that's partially implied by "payments", but it may be worth expanding -- there could also be "Multisig" as another entry

2020-04-07 02:46 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
20bytes cut out of keccak256 (like sha3, but with small difference) of full pubkey

2020-04-07 03:14 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The address for payments/value transfers. Different prefixes of the transfer address are used to distinguish between devnet, testnet and mainnet.
Thanks guys, will also add **Multisig** as well.

2020-04-07 03:17 UTC, yihuang commented on docs/getting-started/technical_glossary.md
> +The penalty imposed on validators' misbehaviour, which resulted in losing some amount of their staked tokens.
for both byzantine faults and liveness faults

2020-04-07 03:19 UTC, yihuang commented on docs/getting-started/technical_glossary.md
> +The general state of a staking address that includes _nonce_, _bounded/unbonded_ amount, and _slashing related information_ (if any).
Also jailing information, validator metadata, etc.

2020-04-07 03:21 UTC, yihuang approved these changes

2020-04-07 03:21 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The general state of a staking address that includes _nonce_, _bounded/unbonded_ amount, and _slashing related information_ (if any).
For jailling info, I put it under _slashing related information_ ;
does validator metadata shows up in the state of just the staking address?

2020-04-07 03:28 UTC, yihuang commented on docs/getting-started/technical_glossary.md
> +The general state of a staking address that includes _nonce_, _bounded/unbonded_ amount, and _slashing related information_ (if any).
> does validator metadata shows up in the state of just the staking address?

Yes, I think so.

2020-04-07 10:48 UTC, CeruleanAtMonaco commented on docs/getting-started/technical_glossary.md
> +The Hierarchical Deterministic wallet is a system of deriving keys from a single starting point known as mnemonic phrase, which can be easily back up and restored.
Should be 
Entropy -> Mnemonic code words;
Mnemonic code words + Salt ---(with key stretching function)---> Seed

2020-04-07 13:52 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +**tmkms**
I will put it as "**Tendermint KMS( tmkms)**" as in [here](https://github.com/iqlusioninc/tmkms#tendermint-kms-).

2020-04-07 16:21 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The address for staking related operations, it follows the format of Ethereum account address.
The most formal reference will be the _Appendix E_ in Eth [yellow paper](http://gavwood.com/paper.pdf), or well, [Wikipedia](https://en.wikipedia.org/wiki/Ethereum#Addresses)

2020-04-08 02:02 UTC, tomtau commented on docs/getting-started/technical_glossary.md
> +The Hierarchical Deterministic wallet is a system of deriving keys from a single starting point known as mnemonic phrase, which can be easily back up and restored.
Yeah, the starting point for (BIP32) HD wallet is a seed. The starting point for a seed is the initial entropy from (BIP39) wordlists and optional passphrase (the BIP39 passphrase is currently not used in the client-* code, but that can be added later)

2020-04-08 07:06 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The penalty imposed on validators' misbehaviour, which resulted in losing some amount of their staked tokens.
https://github.com/crypto-com/chain-docs/pull/122/commits/9fac08998b5c760bfc646a357f684d402e3eda37#diff-7695b07723d66a575a6a04a4f9ccf641R103

2020-04-08 07:08 UTC, lezzokafka commented on docs/getting-started/technical_glossary.md
> +The validator who finalized the block.
https://github.com/crypto-com/chain-docs/pull/122/commits/9fac08998b5c760bfc646a357f684d402e3eda37#diff-7695b07723d66a575a6a04a4f9ccf641R93
See if it looks better now.

2020-04-08 07:18 UTC, calvinaco approved these changes

2020-04-08 10:18 UTC, merged