[Draft] Testnet v0.4 docs update
crypto-com/thaler-docs pull request #133
Opened 2020-04-28 16:17 UTC by lezzokafka

To do list:
- [] Provide the new genesis.json for v0.4([link](https://github.com/crypto-com/chain-docs/compare/master...lezzokafka:v0.4_docs_update?expand=1#diff-8858730c1ec093ea7a43196e843f91ccR44)); 
- [] Replace the `--genesis_app_hash ` flag in the command for starting _chain-abci_  with the new genesis_app_hash ( [link_1](https://github.com/crypto-com/chain-docs/compare/master...lezzokafka:v0.4_docs_update?expand=1#diff-8858730c1ec093ea7a43196e843f91ccR100) and [link_2](https://github.com/crypto-com/chain-docs/compare/master...lezzokafka:v0.4_docs_update?expand=1#diff-8858730c1ec093ea7a43196e843f91ccR175))

2020-04-29 02:53 UTC, tomtau requested changes

2020-04-29 02:53 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
>  - You can download the Linux SGX SDK installers from the Intel Open Source [website](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.8-release). More details can be found in
2.9

2020-04-29 02:53 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
>  ### Step 0. Install Intel SGX SDK 2.8 and other pre-requisites
2.9

2020-04-29 02:53 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
not sure if this changed in 2.9?

2020-05-04 22:22 UTC, lezzokafka commented on docs/getting-started/thaler-testnet.md
>  - You can download the Linux SGX SDK installers from the Intel Open Source [website](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-2.8-release). More details can be found in
Updated

2020-05-04 22:23 UTC, lezzokafka commented on docs/getting-started/thaler-testnet.md
>  ### Step 0. Install Intel SGX SDK 2.8 and other pre-requisites
Updated

2020-05-05 02:01 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
> +Also, please note the [released binary changes](https://github.com/crypto-com/chain/releases/tag/v0.5.0).
link 0.5.1?

2020-05-05 02:03 UTC, lezzokafka commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
Any comments on this? @leejw51crypto @allthatjazzleo

2020-05-05 02:05 UTC, leejw51crypto commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
it's the same as before
```
ps ax | grep aesm -> check whether aesm service is on
ls /dev/isgx -> check whether driver is on
```
can check with above commands

2020-05-05 02:08 UTC, leejw51crypto approved these changes
lgtm

2020-05-05 02:09 UTC, lezzokafka commented on docs/getting-started/thaler-testnet.md
> +Also, please note the [released binary changes](https://github.com/crypto-com/chain/releases/tag/v0.5.0).
Fixed, thanks @tomtau.

2020-05-06 05:12 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
@leejw51crypto I meant the path `/opt/intel/libsgx-enclave-common/aesm/`

2020-05-06 05:13 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
not sure if the default installation path changed

2020-05-06 06:46 UTC, lezzokafka commented on docs/getting-started/thaler-testnet.md
>  - Make sure `aesmd` service is running (you may potentially start it up manually with `LD_LIBRARY_PATH=/opt/intel/libsgx-enclave-common/aesm /opt/intel/libsgx-enclave-common/aesm/aesm_service`).
See page 11 of the [installation guide](https://download.01.org/intel-sgx/sgx-linux/2.9.1/docs/Intel_SGX_Installation_Guide_Linux_2.9.1_Open_Source.pdf)?

2020-05-08 03:28 UTC, merged