Problem:(Fix#143) genesis page is not up to date
crypto-com/thaler-docs pull request #145
Opened 2020-05-28 07:36 UTC by lezzokafka

Solution: 
`getting-started/genesis.md`
- Added section **Fields in genesis**, described all the fields in the genesis file; 
- Added section **Genesis hash** for light client verification and how the hash it's calculated. 

 `technical_glossary.md` and `thaler-testnet.md`
- Typos fixed

2020-05-28 07:40 UTC, devashishdxt commented on docs/getting-started/genesis.md
> +. Specifically, the genesis file includes the following fields:
```suggestion
Specifically, the genesis file includes the following fields:
```

2020-05-28 07:40 UTC, devashishdxt commented on docs/getting-started/genesis.md
> +Light client allows users to access and interact with the blockchain without having to run a full node. To ensure the light client is served by a full node with the correct blockchain data, we can co
```suggestion
Light client allows users to access and interact with the blockchain without having to run a full node. To ensure the light client is served by a full node with the correct blockchain data, we can compute the **genesis hash** locally beforehand and check it against the full node that we are connecting to.
```

2020-05-28 07:47 UTC, devashishdxt approved these changes

2020-05-28 09:24 UTC, tomtau requested changes
for the tendermint generic parameters, it'll be good to clarify more which ones are relevant and how

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +  A unique identifier for the blockchain.
may be good to mention the extra convention with the hexadecimal network id at the end

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    The public information that other nodes can use for key agreement.
keypackage is a part of the the council node structure.
it's this: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#key-packages
with X509 credential with IAS attestation payload embedded in the extension

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    The minimum time increment between consecutive blocks, in milliseconds.
`time_iota_ms`

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    The minimum time increment between consecutive blocks, in milliseconds.
block is a structure

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    - `"max_gas"`:
that's ignored / -1 in chain

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    - `"max_age_num_blocks"`:
this one is to be deprecated / it's again unused by us

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +      The maximum age of evidence, in nanoseconds.
converted to unbonding time

2020-05-28 09:24 UTC, tomtau commented on docs/getting-started/genesis.md
> +    The initial state of the validator set.
matches ones in app_state/council_nodes

2020-05-28 11:07 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +    The initial state of the validator set.
I check it again and seems this `"validator"` field 
`    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }`
is something about the format of the public key only?

2020-05-28 11:09 UTC, yihuang commented on docs/getting-started/genesis.md
> +- `"app_state"`:
the distribution and network_params are under section of app_state.

2020-05-28 11:09 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +    - `"max_gas"`:
Change it to:
`"max_gas"`:
      _The default value is "-1", i.e., no rules about gas are enforced._

2020-05-28 11:09 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +    The minimum time increment between consecutive blocks, in milliseconds.
Sure, chanage it to 
`"block"`:
 The block formation structure.
...
`"time_iota_ms"`
The minimum time increment between consecutive blocks, in milliseconds.

2020-05-28 11:09 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +      The maximum age of evidence, in nanoseconds.
Changed it to:
- `"max_age_duration"`:
_The time duration of unbonding, in nanoseconds._

2020-05-28 11:10 UTC, yihuang approved these changes
"distributions" and "network_params" are under the section "app_state"

2020-05-28 11:11 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +- `"app_state"`:
You are right, let me rearrange this, thanks again!

2020-05-28 11:36 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +    The initial state of the validator set.
Let me change it to:
- `"validator"`
    - `"pub_key_types"`: The supported validator public key types.

2020-05-28 12:18 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +  A unique identifier for the blockchain.
Sure thing. Fixed

2020-05-29 00:27 UTC, tomtau commented on docs/getting-started/genesis.md
> +      The maximum age of evidence, in nanoseconds.
The original description is still valid (evidence older than that age is dropped) -- my comment was meant just to add a note that this corresponds to the unbonding time

2020-05-29 01:29 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +    The public information that other nodes can use for key agreement.
Moved it to the app_state/council_nodes structure,
let me also provide the link in the description.

2020-05-29 01:39 UTC, tomtau requested changes
small tweaks on the descriptions, but otherwise ok

2020-05-29 01:39 UTC, tomtau commented on docs/getting-started/genesis.md
> +      The public information that other nodes can use for key agreement.
"key agreement" is quite generic, less informative and potentially confusing -- e.g. `.tendermint/config/node_key.json` is also used in "key agreement" (in P2P protocol https://docs.tendermint.com/master/tendermint-core/secure-p2p.html )

keypackage is really this payload: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#key-packages + with X509 embedded with IAS attestation payload that's also checked

2020-05-29 01:39 UTC, tomtau commented on docs/getting-started/genesis.md
> +      The time duration of unbonding, in nanoseconds.
it's also for evidence handling -- e.g. evidence older than that is ignored.
and it corresponds to unbonding time

2020-05-29 01:39 UTC, tomtau commented on docs/getting-started/genesis.md
> +  The initial state of the validator set.
and it should match/correspond to the initial "council_nodes" + distribution (i.e. voting power should correspond to the bonded amount in full units)

2020-05-29 06:24 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +  The initial state of the validator set.
I have elaborated it a bit, see if it looks better: 

- `"validators"`:
  The initial state of the validator set.
  - `"address"`: The address of the validator (hash of the validator's public key). Note that the validator is identified by its address.
  - `"name"`: The name of the validator, which should correspond to the name in _"council_nodes"_.
  - `"power"`: The voting power of the validator, which should match with the bonded amount of its related staking address in _"distribution"_ in full units.
  - `"pub_key"`
    - `"type"`: The validator public key types, which should be one of the supported types in _"pub_key_types"_.
    - `"value"`: The base64 encoding of validator's public key, which should correspond to the _"value"_ of the validator in _"council_nodes"_.

2020-05-29 06:30 UTC, lezzokafka commented on docs/getting-started/genesis.md
> +      The time duration of unbonding, in nanoseconds.
Updated it to:
- `"max_age_duration"`:
      The maximum age of evidence, in nanoseconds. Any evidence older than this will be rejected. It is also the "unbonding period", the time duration of unbonding.

2020-05-29 06:35 UTC, merged