Problem: (Fix #161) Local full node deployment pages are not up-to-date and have typos
crypto-com/thaler-docs pull request #162
Opened 2020-06-30 18:07 UTC by calvinlauco

Solution: Update the local full node deployment and send first transaction page

Blocked by: https://github.com/crypto-com/chain/pull/1850

----
Special credits to @diereysaa who spotted the typos and gave us feedback. Thank you!

2020-07-02 01:52 UTC, tomtau reviewed
looks ok, just a few comments -- not sure why `sudo` is needed? or is it because of the docker? if so, why not just adding the user to docker group?

2020-07-02 01:52 UTC, tomtau commented on docs/getting-started/README.md
> +$ sudo make prepare
why sudo? is it running some permission commands? wouldn't it be better if sudo was used inside the makefile where needed rather than the whole make running under sudo?

2020-07-02 01:52 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +$ ./target/debug/client-cli sync --name Default --disable-fast-forward
maybe fast forward shouldn't be a default if it causes issues + it's not secure (if one doesn't run a full node) / can't be used with the light client verification?

2020-07-02 02:55 UTC, calvinlauco commented on docs/getting-started/README.md
> +$ sudo make prepare
The `sudo` is needed for copying the config files
```
copy devnet tendermint config
cp docker/config/devnet/tendermint/config.toml /tmp/data/tendermint/config/
cp: cannot create regular file '/tmp/data/tendermint/config/config.toml': Permission denied
Makefile:106: recipe for target 'init-tendermint' failed
make: *** [init-tendermint] Error 1
```

The default data file path is `/tmp/data`. but the `/tmp` folder is owned by the root.

2020-07-02 02:57 UTC, calvinlauco commented on docs/getting-started/send_your_first_transaction.md
> +$ ./target/debug/client-cli sync --name Default --disable-fast-forward
The main reason driving me to change this is because the Devnet have zero fee and is affected by https://github.com/crypto-com/chain/issues/794

After the issue is fixed we could use the default of fast forward.

2020-07-02 03:07 UTC, lezzokafka reviewed
Looks great, just left a quick comment.
Thanks @calvinaco!

2020-07-02 03:07 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +A pre-created Hierarchical Deterministic(HD) Wallet wallet mnemonic with funds inside are prepared for you in Devnet. You can find it [here](https://github.com/crypto-com/chain/blob/master/docker/con
```suggestion
A pre-created Hierarchical Deterministic(HD) Wallet wallet mnemonic with funds inside are prepared for you in Devnet. Kindly restore the wallet by using this [mnemonic](https://github.com/crypto-com/chain/blob/master/docker/config/devnet/tendermint/mnemonics.txt) before moving on to the next step. 
```

2020-07-02 05:02 UTC, tomtau commented on docs/getting-started/README.md
> +$ sudo make prepare
what about just adding a step with sudo creating the folders + chown/chrgp?

2020-07-06 19:55 UTC, calvinlauco commented on docs/getting-started/README.md
> +$ sudo make prepare
Updated to separate commands:
```
sudo make create-path
sudo make chown-path
make prepare
```

2020-07-07 01:23 UTC, lezzokafka approved these changes

2020-07-07 01:25 UTC, tomtau requested changes
looks ok, but should the PR be now first against `dev`? @allthatjazzleo

2020-07-07 03:40 UTC, allthatjazzleo commented
> looks ok, but should the PR be now first against `dev`? @allthatjazzleo

yes, should create the PR against `dev`

2020-07-07 04:09 UTC, calvinlauco commented
> looks ok, but should the PR be now first against `dev`? @allthatjazzleo

Changed base branch to `dev`

2020-07-07 04:44 UTC, tomtau approved these changes

2020-07-07 04:44 UTC, merged