Problem: (fix #167) missing steps in installing sgx driver and psw
crypto-com/thaler-docs pull request #168
Opened 2020-07-08 10:24 UTC by allthatjazzleo

Solution: Add appendix page to show some steps to install SGX driver and PSW.

2020-07-08 10:43 UTC, tomtau requested changes
the commit with CI/CD may not be necessary?

2020-07-08 10:49 UTC, allthatjazzleo commented
@tomtau 
This forked pr branch is created from master 
I am not sure why the that commit hash (0596bc1) in master is different from the same commit (11e57ca) in dev

2020-07-09 23:30 UTC, tomtau requested changes
why have custom instructions (which only works on Debian-based systems?) and not refer to the official installation guide that has instruction for different distributions?

2020-07-09 23:30 UTC, tomtau commented on docs/getting-started/thaler-testnet.md
> +$ sudo apt install libzmq3-dev clang -y
Is clang necessary for the testnet when one uses the released binary?

2020-07-09 23:30 UTC, tomtau commented on docs/getting-started/appendix.md
> +$ sudo /sbin/depmod
why not just download the released binary -- https://download.01.org/intel-sgx/latest/linux-latest/distro/ubuntu18.04-server/sgx_linux_x64_driver_2.6.0_602374c.bin and run that?

Also if Secure Boot is enabled, one may need to sign the driver?

Not sure why to have these custom instructions and not just to link the official documentation: https://download.01.org/intel-sgx/latest/linux-latest/docs/Intel_SGX_Installation_Guide_Linux_2.10_Open_Source.pdf
(page 7)

2020-07-10 03:21 UTC, allthatjazzleo commented on docs/getting-started/thaler-testnet.md
> +$ sudo apt install libzmq3-dev clang -y
I found clang is installed along with libzmq3-dev in ansible script.
If it is not necessary, I will remove it.

2020-07-10 03:26 UTC, allthatjazzleo commented on docs/getting-started/appendix.md
> +$ sudo /sbin/depmod
https://mcoproduct.atlassian.net/browse/CEV2-223
it may be easier to install from download the released binary.
As, there are some requests to show more steps in installing sgx driver in our documentation.
I guess we can link the official documentation and show custom instructions in appendix at the same time?

2020-07-10 03:48 UTC, tomtau commented on docs/getting-started/appendix.md
> +$ sudo /sbin/depmod
The building steps are described in the official repo: https://github.com/intel/linux-sgx-driver#install-the-intelr-sgx-driver so that doesn't need to be written here either (+ the official repo has steps for different distributions)

2020-07-10 05:42 UTC, allthatjazzleo commented
https://github.com/crypto-com/chain-docs/pull/169 will cover the issue #167
This pr should be closed

2020-07-10 05:42 UTC, closed without merging