Problem: Details of catch-up process and data bootstraping are missing
crypto-com/thaler-docs pull request #207
Opened 2020-08-04 08:51 UTC by devashishdxt

Solution: Updated the "Catch-up process" section in docs. Related to #195.

Note: The other half of #195, i.e., invitation protocol will be done in a separate PR.

2020-08-04 09:41 UTC, tomtau requested changes

2020-08-04 09:41 UTC, tomtau commented on docs/modules/tdbe.md
> +TODO: Should this process also include creating and spending UTXOs or should that be done during tendermint
> TODO: Should this process also include creating and spending UTXOs or should that be done during tendermint synchronization process?

Since here, it'll follow block-by-block, it'll still need to know how to reply when -- so probably needs to temporarily mark for these prefetched transactions the expected block height when they are created?

2020-08-04 09:41 UTC, tomtau commented on docs/modules/tdbe.md
> +`tx-validation` until `last_fetched_block`. `chain-abci` should still do a basic validation and update UTXOs.
only tx-validation of withdraw/transfer

2020-08-04 09:41 UTC, tomtau commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
verify  `transaction_id`s / block_results against app hash?

2020-08-04 09:41 UTC, tomtau commented on docs/modules/tdbe.md
> +current node to `current_block_height` on remote node.
the original meaning in that sentence was "genesis skip" was as in some flag to denote "skip this / don't do this -- this node is being started up at genesis, no need for any catch up", so this revised sentence is the opposite

2020-08-05 05:46 UTC, devashishdxt commented on docs/modules/tdbe.md
> +current node to `current_block_height` on remote node.
Changed.

2020-08-05 05:46 UTC, devashishdxt commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
Added verification step.

2020-08-05 05:46 UTC, devashishdxt commented on docs/modules/tdbe.md
> +`tx-validation` until `last_fetched_block`. `chain-abci` should still do a basic validation and update UTXOs.
Changed.

2020-08-05 06:00 UTC, devashishdxt commented on docs/modules/tdbe.md
> +TODO: Should this process also include creating and spending UTXOs or should that be done during tendermint
Can you elaborate? I'm not sure if I understand what you mean correctly.

2020-08-05 06:10 UTC, tomtau commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
shouldn't that step be before fetching them / putting them in a chunk? if txid verification with `app_hash` doesn't match, why would want even want to continue fetching from that node?

2020-08-05 06:10 UTC, tomtau commented on docs/modules/tdbe.md
> +basic validation and update UTXOs.
to reduce ambiguity how this will be "skipped" -- is something like:
* if block_height < last_fetched_block AND (tx type == `transfer` OR tx type == `withdraw`) AND tx is in storage, check output size matches AND tx inputs are unspent -> valid skip / (create tx output metadata, put in merkle tree etc.)
* if block_height < last_fetched_block AND (tx type == `transfer` OR tx type == `withdraw`) AND tx is NOT in storage -> skip as invalid
* if block_height < last_fetched_block AND tx type != `transfer` AND tx type != `withdraw`), do normal tx validation

?

2020-08-05 06:11 UTC, tomtau reviewed
looks ok, sans some ambiguity

2020-08-05 06:15 UTC, tomtau commented on docs/modules/tdbe.md
> +TODO: Should this process also include creating and spending UTXOs or should that be done during tendermint
https://github.com/crypto-com/chain-docs/pull/207#discussion_r465495050

maybe just the fact they are in storage implicitly means that during "skipping", they are considered "valid"?

if abci runs, it still needs to know which tx is valid (even if it was prefetched transfer/withdraw), so that it can compute and return the same app hash for a particular block

2020-08-05 06:24 UTC, devashishdxt commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
What is "txid verification with `app_hash`"?

2020-08-05 07:34 UTC, yihuang commented on docs/modules/tdbe.md
> +When a node starts, it should first check the configuration parameter `perform_catchup`. If `perform_catchup` is `true`,
is this `perform_catchup` parameter necessary, is can decide this at runtime?

2020-08-05 08:02 UTC, devashishdxt commented on docs/modules/tdbe.md
> +When a node starts, it should first check the configuration parameter `perform_catchup`. If `perform_catchup` is `true`,
This parameter should be provided during startup. Currently, `tdbe` assumes this to be `true` when a remote TDBE address is present in command line options.

2020-08-05 08:02 UTC, devashishdxt commented on docs/modules/tdbe.md
> +basic validation and update UTXOs.
Added

2020-08-05 08:04 UTC, tomtau commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
you get a list of valid txids --> compute the merkle tree root out of them --> is this merkle root the component of the retrieved app hash for a particular block?

2020-08-05 09:20 UTC, devashishdxt commented on docs/modules/tdbe.md
> +  - Call `block_results` on remote node's tendermint RPC for each chunk. For each `block_results` in the response:
Done.

2020-08-05 10:00 UTC, tomtau approved these changes

2020-08-06 01:53 UTC, devashishdxt commented
@tomtau Can we merge this?

2020-08-06 02:01 UTC, merged