(CEV2-266) Problem: Missing ClientRPC documentation UI
crypto-com/thaler-docs pull request #208
Opened 2020-08-05 10:11 UTC by cdc-Hitesh

- Added postman collection for supported endpoints
- Added JSON RPC Methods Documentation

2020-08-05 10:12 UTC, allthatjazzleo commented
/staging

2020-08-05 10:29 UTC, allthatjazzleo commented
/staging

2020-08-06 10:15 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **latest_block_time**             |  *TimeStamp*, String | Latest block time [Tendermint timestamps](https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md#time)  |
```suggestion
| **latest_block_time**             |  *TimeStamp*, String | Latest block time [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time)  |
```

2020-08-06 10:23 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md#time) |
```suggestion
| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time) |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **app_state**             | *Data*, String | Validator display names  |
```suggestion
| **app_state**             | *Data*, String | The application state  |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md#time) |
```suggestion
| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time) |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **latest_block_time**             |  *TimeStamp*, String | Latest block time [Tendermint timestamps](https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md#time)  |
```suggestion
| **latest_block_time**             |  *TimeStamp*, String | Latest block time [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time)  |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.kind**             |  *Data*, String  | Why reason? Possible Values: `NonLive` or `ByzantineFault`|
```suggestion
| **last_slash.kind**             |  *Data*, String  | Last slashing type. Possible Values: `NonLive` or `ByzantineFault`|
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.amount**             |  *Quantity*, Uint64  | How much amount |
```suggestion
| **last_slash.amount**             |  *Quantity*, Uint64  | Last slashing amount |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.kind**             |  *Data*, String  | Why reason? Possible Values: `NonLive` or `ByzantineFault`|
```suggestion
| **last_slash.kind**             |  *Data*, String  |  Last slashing type. Possible Values: `NonLive` or `ByzantineFault`|
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.amount**             |  *Quantity*, Uint64  | How much amount |
```suggestion
| **last_slash.amount**             |  *Quantity*, Uint64  |  Last slashing amount. |
```

2020-08-06 11:13 UTC, lezzokafka commented on docs/api/client-rpc.md
> +This documents lists all the RPC methods available on top of the `client-rpc` component.
```suggestion
This document lists all the RPC methods available on top of the `client-rpc` component.
```

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +@Todo - Do we need to give hyperlink to what does these terms mean?
Nice catch, I think we dont have something very clear on the address types  in the "Protocol Design " (but the updated tech whitepaper does). 
I will update [Transaction Accounting Model](https://chain.crypto.com/docs/protocol/transaction-accounting-model.html#utxo-accounts-model) to provided more detail on this.

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +@Todo - Do we need to give hyperlink to what does these terms mean?
You might also want to mention that the transfer address prefixes is Chain ID depended, see more in [chain id](https://chain.crypto.com/docs/protocol/chain-id-and-network-id.html#chain-id): 
For example, if the network is testnet, you will get a transfer address in the form of `tcroxxxx....xxxx`, for mainnet, it will be `croxxxx....xxxx`. 

Also note that it is universal for staking address, i.e. staking address is **not** Chain ID depended.

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +* To download available methods as a **POSTMAN** Collection, [click here](https://github.com/cdc-Hitesh/chain-docs/tree/master/docs/api/client-rpc-methods.postman_collection.json)
Should that be the `crypto-com/chain-docs` repo?

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Restores a `HD` or `HW` type wallet. //@Todo: need hyperlink ?
This [link](https://chain.crypto.com/docs/wallets/client-cli.html#wallet-new-create-a-new-wallet) could be helpful.

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +`result` : *String* - Wallet Authentication Token or Secret Key. //@Todo : This is `enckey`, so hyperlink?
It returns the` Authentication Token`, where it is required for all authorised commands.

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Restore a `Basic` type wallet. //@Todo - hyperlink needed to explain wallet types?
See if think [link](https://chain.crypto.com/docs/wallets/client-cli.html#wallet-operations) helps.

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Depositing the staked amount to a recipient address.
```suggestion
Depositing the staked amount to a recipient staking address.
```

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Withdraws all unbonded tokens to a destination address.
```suggestion
Withdraws all unbonded tokens to a destination transfer address.
```

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Initiate the unjailing process for the `jailed` tokens.
```suggestion
Initiate the unjailing process for a `jailed` staking address.
```

2020-08-06 12:06 UTC, lezzokafka commented on docs/api/client-rpc.md
> +It can be used to create a `m-of-n` multisig wallet. Where `m` is the minimum number of signatures required, `n` is the total number of parties.
Can add sth like "n has to be greater or equal to m"

2020-08-07 04:27 UTC, cdc-Hitesh commented on docs/api/api-objects.md
> +| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/blockchain.md#time) |
Oh the link is different. thanks

2020-08-07 04:28 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +It can be used to create a `m-of-n` multisig wallet. Where `m` is the minimum number of signatures required, `n` is the total number of parties.
Okay good one i will do it

2020-08-07 04:37 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +`result` : *String* - Wallet Authentication Token or Secret Key. //@Todo : This is `enckey`, so hyperlink?
Great thanks.

2020-08-07 04:37 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +Restore a `Basic` type wallet. //@Todo - hyperlink needed to explain wallet types?
Hyperlink this one for now

2020-08-07 04:38 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +* To download available methods as a **POSTMAN** Collection, [click here](https://github.com/cdc-Hitesh/chain-docs/tree/master/docs/api/client-rpc-methods.postman_collection.json)
I am not sure, Should I better keep it off the repo?

2020-08-07 04:40 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +@Todo - Do we need to give hyperlink to what does these terms mean?
Yes yes. I get this. Let me refer this/

2020-08-07 07:33 UTC, calvinaco commented on docs/api/client-rpc.md
> +* To download available methods as a **POSTMAN** Collection, [click here](https://github.com/cdc-Hitesh/chain-docs/tree/master/docs/api/client-rpc-methods.postman_collection.json)
It is better put the maintained collection in Crypto.com repository or hosted on Crypto.com website.

2020-08-09 20:21 UTC, calvinlauyh requested changes
Great content, the overall format looks good to me. A few points to note:

- The description, response format are inconsistent across methods. For example `TX_ID` has different upper/lower cases in different method calls. I notice the description sometimes start with a verb, and sometimes has a `s` suffix like `Creates` but sometimes not. Some technical terms has its first letter capitalized but some are not. It is better to have a standard and used it across the whole doc.
- Some of the request/response is missing. So I put an unresolved block over those parts to keep track of them.

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* JSONRPC requests can be `POST`'d to the root RPC endpoint via HTTP. Example below:
```suggestion
* To call a JSONRPC method, send a HTTP `POST` request to the root RPC endpoint. Example below:
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Create a Watch only Transfer type address.
```suggestion
Imports a watch only transfer address.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *String* - Public key used in Crypto.com Chain.
```suggestion
* *String* - Secp256k1 public key of the transfer address in either compressed or uncompressed form.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Retrieve Wallet Encryption / Authentication token. Keep the token safe and it will be needed for all authorized commands.
```suggestion
Retrieve Wallet Encryption / Authentication token. The token can be used to unlock all authorized wallet methods.

:::: warning Encryption Token Storage
Keep the token in a safe place because it can unlock any authorized wallet methods. Exposing your token may result in lost of funds.
:::
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +    //2, 100, false
Remove`//`?

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *Boolean* - if `true` returns in reverse-chronological order. //@Todo - wording needs to change or ok?
```suggestion
* *Boolean* - Returns transfer addresses in reverse-chronological order of creation date if the value is `true`.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *String* - Signed raw transaction. //@Todo: need to specify something specific here ?
```suggestion
* *String* - Hex encoded signed transfer transaction.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +`result` : *String* - Transaction ID (Hex Encoded). // @Todo: tx_id needs to be hyperlinked ?
Yes, you can link to here: https://chain.crypto.com/docs/protocol/transaction.html#transaction-identifier in relative path.

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *String* - valid Mnemonic phrase. (eg. `alpha beta charlie .. . . . .  . zeta`)
```suggestion
* *String* - valid Mnemonic phrase. (e.g. `alpha beta charlie .. . . . .  . zeta`)
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +`result` : *String* - Wallet Authentication Token or Secret Key.
```suggestion
`result` : *String* - Wallet Authentication Token.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +`result` : *String* - Wallet Authentication Token or Secret Key. //@Todo : This is `enckey`, so hyperlink?
Suggest to remove `or Secret Key`

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *Uint64* - Amount to send in base unit (to be Stringified).
What does it mean by `to be Stringified`

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Create a raw transaction to be broadcasted separately at [wallet_broadcastSignedTransferTx](#wallet_broadcastSignedTransferTx) endpoint.
```suggestion
Create a raw transfer transaction to be broadcasted separately at [wallet_broadcastSignedTransferTx](#wallet_broadcastSignedTransferTx) endpoint.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *String* - Destination/To Address.
`Destination/To Address.` is duplicated in meaning. Can be simplified into `To address`

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Create a raw transaction to be broadcasted separately at [wallet_broadcastSignedTransferTx](#wallet_broadcastSignedTransferTx) endpoint.
However, I don't think the transaction created by this method is signed. So it cannot be broadcasted by `wallet_broadcastSignedTransferTx` actually.

The comment of `UnsignedTransaction`:

> /// When withdraw some coin from an offline wallet(W_A),the struct is build from an
> /// `watch-only` wallet(W_B) associated with the offline wallet. We can dump the structure
> /// from W_A and load it into the W_B so that W_B can make a signed transaction then send
> /// it to online W_A by USB storage or email, W_A then broadcast the signed transaction

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +    "result": "<<Raw transaction HEX string>>",
```suggestion
    "result": "<<Base64 encoded unsigned transfer transaction>>",
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +    "result": "<<Wallet Authentication Token>>", //@Todo
Already handled by [previous conversation](https://github.com/crypto-com/chain-docs/pull/208/files#r466350747)?

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +* *Boolean* - set `true` to return transactions in *latest-first* fashion. //@Todo - change the sentence ?
```suggestion
* *Boolean* - Return transactions in latest-first order if the value is `true`.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +@Todo fill the response
Resolve this when this is done

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +@Todo
Resolve this when this is done.

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +@ToDo
Resolve this when this is done.

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +@Todo: Body here
Resolve this when this is done.

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Endpoint used for staking unbonded tokens.
```suggestion
Unbonding staked(bonded) amount of a wallet staking address.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Initiate the unjailing process for a `jailed` staking address.
```suggestion
Unjailing a `jailed` wallet staking address.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Adds a partial signature to a multisig_transaction.
```suggestion
Adds a partial signature from other co-signers to an existing multiSig transaction session.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Initiate a new multisig partial signature for a multisig_session.
```suggestion
Partially sign an existing multiSig transaction session and returns the partial signature.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Create a new nonce commitment for a `multisig_session_id`.
```suggestion
Creates and returns the nonce commitment for an existing multiSig transaction session.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Create a new session ID for a multiSig transaction.
```suggestion
Create a new multiSig transaction session.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +`result` : *String* - Serialised nonce value.
```suggestion
`result` : *String* - Serialized nonce value.
```

2020-08-09 20:21 UTC, calvinlauyh commented on docs/api/client-rpc.md
> +Requests a new nonce for the multisig transaction.
```suggestion
Returns nonce for the existing multiSig transaction session.
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +Start applying the multisig signature process.
```suggestion
Returns the final signature of an existing multiSig transaction session.
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +Signs a provided unsigned transaction and broadcast it to the blockchain.
```suggestion
Creates and attaches the final signature of an existing multiSig transaction session to the corresponding unsigned transaction provided and broadcast it to the blockchain.
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +***Body: //@Todo : complete body below***
Resolve this when this is done.

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +    "result": "<<tx_id>>",
```suggestion
    "result": "<<TX_ID>>",
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +    "result": "<<tx_id>>",
```suggestion
    "result": "<<TX_ID>>",
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +    "result": "<<tx_id>>",
```suggestion
    "result": "<<TX_ID>>",
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +    "result": "<<Tx_ID>>",
```suggestion
    "result": "<<TX_ID>>",
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +***@Todo :Complete body below Body:***
Resolve this when this is done

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +//@todo: complete response
Resolve this when this is done

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +Create a Watch only Staking address.
```suggestion
Imports a watch only staking address.
```

2020-08-09 20:21 UTC, calvinlauco commented on docs/api/client-rpc.md
> +* *String* - Public key used in Crypto.com Chain. [@ToDo - Any technical language to be put here?]
```suggestion
* *String* - Secp256k1 public key of the staking address in either compressed or uncompressed form.
```

2020-08-10 08:02 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +    //2, 100, false
I kept it intentionally, though they are optional arguments actual RPC call wasn't accepting these parameters

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.amount**             |  *Quantity*, Uint64  | How much amount |
```suggestion
| **last_slash.amount**             |  *Quantity*, Uint64  | Last slashing amount. |
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.time**             |  *Timestamp*, String  | Timestamp ISO Format|
```suggestion
| **last_slash.time**             |  *Timestamp*, String  | Last slashing time, in ISO format.|
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **last_slash.time**             |  *Timestamp*, String  | Timestamp ISO Format|
```suggestion
| **last_slash.time**             |  *Timestamp*, String  | Last slashing time, in ISO format.|
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **max_age_duration**             |  *Nubmer*, UnsignedInt64 | Max age duration |
```suggestion
| **max_age_duration**             |  *Nubmer*, UnsignedInt64 | Maximum age of evidence ( in nanoseconds)|
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **max_age_duration**             |  *Nubmer*, UnsignedInt64 | Max age duration |
```suggestion
| **max_age_duration**             |  *Nubmer*, UnsignedInt64 | Maximum age of evidence ( in nanoseconds)|
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **proposer_priority**             |  *Data*, String | Validator proposer priority Can be an integer value or `null`   |
```suggestion
| **proposer_priority**             |  *Data*, String | Validator proposer priority, can be an integer value or `null`   |
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/client-rpc.md
> +Returns the Genesis information of the network.
Can point to https://chain.crypto.com/docs/protocol/genesis.html.

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/client-rpc.md
> +    "result": "7befc23ec5a9e.......3b995d156e488b3615d9e9e7c4",
```suggestion
    "result": "<<Wallet View Key>>",
```

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/client-rpc.md
> +    "result": "7befc23ec5a9e.......3b995d156e488b3615d9e9e7c4",
Note: I think its okay if you want to keep the format similar to "list address", such as:
- https://github.com/crypto-com/chain-docs/pull/208/files#diff-d0429026097964583a9f8d9023cb0017R689
- https://github.com/crypto-com/chain-docs/pull/208/files#diff-d0429026097964583a9f8d9023cb0017R781
etc

2020-08-10 10:04 UTC, lezzokafka commented on docs/api/client-rpc.md
> +* *String* - Destination/To Address.
Same as https://github.com/crypto-com/chain-docs/pull/208/files#diff-d0429026097964583a9f8d9023cb0017R1025

2020-08-11 09:05 UTC, cdc-Hitesh commented on docs/api/api-objects.md
> +| **max_age_duration**             |  *Nubmer*, UnsignedInt64 | Max age duration |
Looks great.

2020-08-11 09:08 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +Returns the Genesis information of the network.
Ok done.

2020-08-11 20:09 UTC, cdc-Hitesh commented on docs/api/client-rpc.md
> +* *String* - Destination/To Address.
Thanks for pointing out.

2020-08-12 07:55 UTC, calvinlauco commented
/staging

2020-08-14 01:47 UTC, calvinlauco commented
/staging

2020-08-14 02:55 UTC, calvinlauyh requested changes

2020-08-14 02:55 UTC, calvinlauco commented on docs/api/client-rpc.md
> +    "result": "<<tx_id>>",
@cdc-Hitesh

2020-08-14 02:55 UTC, calvinlauco commented on docs/api/client-rpc.md
> +@ToDo
@cdc-Hitesh

2020-08-14 02:55 UTC, calvinlauco commented on docs/api/client-rpc.md
> +`result` : *String* - Serialised nonce value.
@cdc-Hitesh

2020-08-14 05:39 UTC, calvinlauco commented
/staging

2020-08-17 02:50 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **p2p**           | *Quantity*, Int64   | default: 7 , P2P protocol Version. |
```suggestion
| **p2p**           | *Quantity*, Int64   | default: `7` , P2P protocol Version. |
```

2020-08-17 02:50 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **genesis_time**           | *Timestamp*, String   | Time of Genesis. [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time). |
```suggestion
| **genesis_time**           | *Timestamp*, String   | Time of Genesis, see [Tendermint timestamps](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#time). |
```

2020-08-17 02:50 UTC, lezzokafka commented on docs/api/api-objects.md
> +| **type**           | *Data*, String  | [read here](https://docs.tendermint.com/master/spec/blockchain/encoding.html). |
Not sure if this is the correct link for it? @allthatjazzleo

2020-08-18 06:18 UTC, leejw51crypto approved these changes
lgtm

2020-08-18 14:00 UTC, calvinaco commented
/staging

2020-08-18 14:00 UTC, calvinlauco commented
/staging

2020-08-19 03:15 UTC, cdc-Hitesh commented on docs/api/api-objects.md
> +| **type**           | *Data*, String  | [read here](https://docs.tendermint.com/master/spec/blockchain/encoding.html). |
updating it to https://docs.tendermint.com/master/spec/core/encoding.html#public-key-cryptography

2020-08-19 05:13 UTC, lezzokafka approved these changes
@cdc-Hitesh Thanks for the the efforts in completing this huge PR! 👍

2020-08-19 08:55 UTC, calvinlauco approved these changes
Awesome. LGTM!

2020-08-19 08:56 UTC, merged