Problem (Fix #191): nodejoin tx validation is not revised with tdbe
crypto-com/thaler-docs pull request #209
Opened 2020-08-07 01:44 UTC by yihuang

Solution:
- add mlsinit validation rules
- add community node into staking state transition

2020-08-07 02:33 UTC, tomtau requested changes
a few comments

2020-08-07 02:33 UTC, tomtau commented on docs/modules/staking-state.md
> +    pub leaf_index: LeafSize,
In code, `NodeCommonInfo` is currently used in the node join tx payload as well -- it captured the common parts of metadata from 0.5 council node, so that the tx format isn't broken.
One thing to clarify is whether the "node join tx" payload will use a different struct (as the "leaf index" should be already contained in the Add proposal that's in "confidential init"?) for this metadata that's still compatible with the wire format or if nodejoin tx payload gets broken in 0.6 (there are potentially other breaking changes https://github.com/crypto-com/chain/pull/2071#issuecomment-669676234 )

2020-08-07 02:33 UTC, tomtau commented on docs/modules/staking-state.md
>  `validator.inactive_time.is_none()`
all these are then assumed to be `node.unwrap().validator`?

2020-08-07 02:33 UTC, tomtau commented on docs/modules/staking-state.md
> +
\+ not jailed?

2020-08-07 02:33 UTC, tomtau commented on docs/modules/transactions.md
> +  - Validator address not banned if join validator
not banned? was that banlist of byzantine validator keys? maybe not relevant?

2020-08-07 02:33 UTC, tomtau commented on docs/modules/transactions.md
> +    let (init_secret, commit_secret, group_context) = get_from_TDBE(epoch);
could this be obtained just from the epoch? one will need the add proposal to compute the updated tree's hash? and will need a commit to compute the transcript_hash?

2020-08-07 02:33 UTC, tomtau commented on docs/modules/staking-state.md
> +#### Validator node
there's no "Validator node" -- there's "council node"

the terminology may be a bit inconsistent in this doc:
* validator == actor that may run several community nodes and council node
(also validator == node with consensus pubkey in TM validatorupdate )
* council node == application specific node metadata + TM consensus pubkey
* community node == application specific node metadata
* full node / sentry node / ... == instantiations / usage of community nodes

2020-08-07 02:44 UTC, yihuang commented on docs/modules/staking-state.md
> +
since it only transit from "clean staking" state, which means all the validator stuff has finished and cleaned up.

2020-08-07 02:45 UTC, yihuang commented on docs/modules/staking-state.md
>  `validator.inactive_time.is_none()`
yes

2020-08-07 02:49 UTC, yihuang commented on docs/modules/transactions.md
> +    let (init_secret, commit_secret, group_context) = get_from_TDBE(epoch);
can TDBE send (init_secret, commit_secret, group_context) to TVE, TVE use it to verify abci request?

2020-08-07 03:14 UTC, tomtau commented on docs/modules/transactions.md
> +    let (init_secret, commit_secret, group_context) = get_from_TDBE(epoch);
there are two possibilities -- either it'll push these altogether (TVE can then derive the exporter secret), or it'll expose some `verify-confirmation-from-new-add` function

2020-08-07 03:21 UTC, tomtau commented on docs/modules/staking-state.md
> +
ok, makes sense -- so "clean staking" will be the base state that both begin with or return to.


maybe a quick state diagram would be helpful.

2020-08-07 20:22 UTC, yihuang commented on docs/modules/staking-state.md
> +    pub leaf_index: LeafSize,
I think there's no need to bring `ConfidentialInit` into the staking state, it'll take storage space in the staking merkle tree. so it's not the same structure as in the tx payload, I'll rename it to avoid confusion.
maybe we'll figure out how to share the other parts of fields better between state and tx payload.

2020-08-07 20:46 UTC, yihuang commented on docs/modules/transactions.md
> +  - Validator address not banned if join validator
removed

2020-08-07 20:51 UTC, yihuang commented on docs/modules/transactions.md
> +    let (init_secret, commit_secret, group_context) = get_from_TDBE(epoch);
added that delegating to TDBE is a potential implementation.

2020-08-07 20:56 UTC, yihuang commented on docs/modules/staking-state.md
> +    pub leaf_index: LeafSize,
adopted the naming choice in tdbe.md now, aka: `NodeDetails` and `CommunityNode`.

2020-08-07 22:00 UTC, yihuang commented on docs/modules/staking-state.md
> +
state diagram added.

2020-08-07 22:05 UTC, yihuang commented on docs/modules/staking-state.md
> +#### Validator node
changed from `validator node` to `council node` in the section title, not sure how should it be changed in other places.

2020-08-10 03:22 UTC, tomtau approved these changes

2020-08-10 03:22 UTC, tomtau commented on docs/modules/transactions.md
> +```
one thing to clarify is that this is only in abci, as TDBE will only update after it's been block-committed.

Normally then, this should prevent the concurrent updates (only one nodejoin will be valid -- the other one can be regenerated later against the latest epoch). Given TDBE internal state only updates after block-committed changes, it won't be possible to generate more than one valid nodejoin per block (I mean they can be generated, but only one will be valid)... so maybe one invariant is that epoch and public ratcheting tree are at most updated once per block?

2020-08-10 03:50 UTC, yihuang commented on docs/modules/transactions.md
> +```
> one thing to clarify is that this is only in abci, as TDBE will only update after it's been block-committed.
> 
> Normally then, this should prevent the concurrent updates (only one nodejoin will be valid -- the other one can be regenerated later against the latest epoch). Given TDBE internal state only updates after block-committed changes, it won't be possible to generate more than one valid nodejoin per block (I mean they can be generated, but only one will be valid)... so maybe one invariant is that epoch and public ratcheting tree are at most updated once per block?

Does the epoch validator rule forbid multiple valid node join naturally? because one can only generate new valid commit after last commit processed?

2020-08-10 04:10 UTC, tomtau commented on docs/modules/transactions.md
> +```
yes, unless there's a bug to force tdbe generate payloads for not-committed epochs

2020-08-10 04:10 UTC, merged

2020-08-10 04:11 UTC, yihuang commented on docs/modules/transactions.md
> +```
Added a validation rule that the add/commit messages are signed by left-most leaf node.