Problem: Details of invitation protocol of TDBE are missing
crypto-com/thaler-docs pull request #210
Opened 2020-08-07 06:16 UTC by devashishdxt

Solution: Added details for invitation protocol in TDBE docs. Fixes #195.

2020-08-07 06:44 UTC, tomtau requested changes
a good start, but some details missing / are to be clarified -- probably also good to sync up with the related https://github.com/crypto-com/chain-docs/pull/209

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +  - New node, after receiving a response from remote TDBE server, verifies it and starts the whole process again (with a
> verifies it and starts the whole process again

if it doesn't verify, then start the whole process again -- otherwise it's good to go

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +  - New node, after receiving a response from remote TDBE server, verifies it and starts the whole process again (with a
also "verifies it" is missing the detail how to verify it

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +  - New node, after receiving a response from remote TDBE server, verifies it and starts the whole process again (with a
My guess is that it'll be something like this:
1. try initialising its own state from the Welcome message: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#welcoming-new-members
2. Check Add / Commit similarly to https://github.com/crypto-com/chain-docs/pull/209/files#diff-8e112651c7b3d2293370b59567ddaddaR253 (minus the "abci state machine" / TVE) against the internal group state (if step 1 was successful) -- for the keypackage perhaps verify that it's the one submitted in the request

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +    - Merkle proof of new node's associated staking state.
detail missing here:
 how does one get the proof? will the node operator just enter its staking state address and tdbe will retrieve it from the remote node against the latest block?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +- If the `NodeJoinTx` is accepted in a block, new node can start to operate normally (as `Commit` with Add-only proposal
some details missing here:
1. how to pass back the tx payload for signature to the node operator? assuming the signing may/will happen on a different machine -- perhaps dump binary to a file (the node operator can download or copy base64 version of it) + print out the txid (+ other details -- e.g. the keypackage?) in the console (that the node operator can take note of and verify when signing)
2. what should happen in the meantime? should tdbe keep checking blocks for this txid and automatically go forward, or wait for a manual signal?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
>  TODO: fetch keypackages/leaf nodes? https://github.com/mlswg/mls-protocol/issues/344
this can be removed and it can be clarified that the tree nodes will be contained in the "ratchet_tree" extension of the Welcome message

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +    staking_state_proof: Proof,
https://github.com/crypto-com/chain/blob/master/chain-storage/src/jellyfish.rs#L121 ?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +- Remote node's TDBE server verifies the merkle proof of node's staking state and also perform validations on
probably verifier that the "staking state" is "clean": https://github.com/crypto-com/chain-docs/pull/209/files#diff-dabdf7fcbd02885e757f294db092869bR58 (it's a starting point for valid node joins for both community and council nodes)?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +    commit: Vec<u8>,
these will be MLSPlaintext.

what about `Welcome`?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +    error_message: Option<String>,
or make it Enum / Result?

2020-08-07 06:44 UTC, tomtau commented on docs/modules/tdbe.md
> +  - New node, after receiving a response from remote TDBE server, verifies it and starts the whole process again (with a
@yihuang

2020-08-10 04:54 UTC, devashishdxt commented on docs/modules/tdbe.md
> +    - Merkle proof of new node's associated staking state.
@tomtau If the TDBE server gets the proof from remote node against the latest block, can we just send the staking state address in `InvitationRequest`?

2020-08-10 05:06 UTC, tomtau commented on docs/modules/tdbe.md
> +    - Merkle proof of new node's associated staking state.
yes, that's a possibility -- requestor sends just the address; responder looks up the state + proof and verifies it's ok ("clean staking")

2020-08-10 06:28 UTC, devashishdxt commented on docs/modules/tdbe.md
> +    error_message: Option<String>,
Changed this. Now both request and response are variants of `TrustedTdbeRequest` and `TrustedTdbeResponse`.

2020-08-10 06:28 UTC, devashishdxt commented on docs/modules/tdbe.md
> +    commit: Vec<u8>,
Done

2020-08-10 06:28 UTC, devashishdxt commented on docs/modules/tdbe.md
> +- Remote node's TDBE server verifies the merkle proof of node's staking state and also perform validations on
Done

2020-08-10 06:28 UTC, devashishdxt commented on docs/modules/tdbe.md
> +    staking_state_proof: Proof,
Removed proof. Now, requestor only sends their staking address.

2020-08-10 06:29 UTC, devashishdxt commented on docs/modules/tdbe.md
>  TODO: fetch keypackages/leaf nodes? https://github.com/mlswg/mls-protocol/issues/344
Done

2020-08-10 06:29 UTC, devashishdxt commented on docs/modules/tdbe.md
> +- If the `NodeJoinTx` is accepted in a block, new node can start to operate normally (as `Commit` with Add-only proposal
Done

2020-08-10 06:29 UTC, devashishdxt commented on docs/modules/tdbe.md
> +    - Merkle proof of new node's associated staking state.
Done

2020-08-10 06:36 UTC, devashishdxt commented on docs/modules/tdbe.md
> +  - New node, after receiving a response from remote TDBE server, verifies it and starts the whole process again (with a
Added verification details in `Invitation protocol` section.

2020-08-10 06:39 UTC, tomtau approved these changes

2020-08-10 06:39 UTC, merged