Problem (Fix #196): details of TDBE usage of light client are missing
crypto-com/thaler-docs pull request #220
Opened 2020-08-18 13:28 UTC by yihuang

Solution:
- add light client verification steps

2020-08-18 15:17 UTC, leejw51crypto commented on docs/modules/tdbe.md
> +  the proocess.
the process?

2020-08-18 15:18 UTC, leejw51crypto approved these changes
lgtm

2020-08-19 03:22 UTC, tomtau requested changes
looks good, but it reverted some changes from https://github.com/crypto-com/chain-docs/pull/217/files

2020-08-19 03:22 UTC, tomtau commented on docs/modules/tdbe.md
this reverts the changes/recent revision

2020-08-19 03:22 UTC, tomtau commented on docs/modules/tdbe.md
> +- New node constructs `NodeJoinTx` (for council or community node) and submits the transaction after getting it signed
only for community node -- then there'll be another node join after the sync up if one wishes to continue as council node

2020-08-19 03:25 UTC, yihuang commented on docs/modules/tdbe.md
> +- New node constructs `NodeJoinTx` (for council or community node) and submits the transaction after getting it signed
yes, it's by accident, fixed.

2020-08-19 03:25 UTC, yihuang commented on docs/modules/tdbe.md
it's by accident, fixed.

2020-08-19 03:25 UTC, yihuang commented on docs/modules/tdbe.md
> +  the proocess.
fixed

2020-08-19 03:31 UTC, tomtau approved these changes

2020-08-19 03:32 UTC, merged