Add incentive design docs
crypto-com/thaler-docs pull request #34
Opened 2019-12-02 09:06 UTC by yihuang

2019-12-02 09:12 UTC, tomtau requested changes
this doc: https://crypto-com.github.io/getting-started/staking.html#rewards contains old sketch, so probably modify it there, or break down the outdated staking document into several pages

2019-12-02 11:07 UTC, yihuang commented
> this doc: https://crypto-com.github.io/getting-started/staking.html#rewards contains old sketch, so probably modify it there, or break down the outdated staking document into several pages

Done, I've updated the rewards section in staking docs.

2019-12-03 01:05 UTC, lezzokafka approved these changes
Looks good to me, thanks Yi :)
I will further polish it, no worries.

2019-12-03 01:30 UTC, tomtau commented on docs/getting-started/staking.md
> +- Slashings of byzantine nodes
```suggestion
- Slashing of byzantine and non-live nodes
```

2019-12-03 01:34 UTC, tomtau commented on docs/getting-started/staking.md
> +    pub remaining: Coin, // total available amount
```suggestion
    pub period_bonus: Coin, // rewards accumulated from fees and slashing
```

2019-12-03 01:39 UTC, yihuang commented on docs/getting-started/staking.md
> +- Slashings of byzantine nodes
Done

2019-12-03 01:44 UTC, tomtau requested changes
looks ok, but one small clarification of where the rewards go before merging it and @lezzokafka editing further

2019-12-03 01:44 UTC, tomtau commented on docs/getting-started/staking.md
> +The rewards validator receives goes directly to the unbonded balance of their staking account.
going to `bonded` balance may be preferable, as one will get a compounding effect (the higher voting power, the more often selected for proposing blocks) + a flexibility of management when to unbond and withdraw rewards from multiple periods.
Or any reason why in unbonded @yihuang ?

2019-12-03 01:53 UTC, yihuang commented on docs/getting-started/staking.md
> +The rewards validator receives goes directly to the unbonded balance of their staking account.
I just think unbonded would be simpler and a little bit less risky then bonded, because the later will change voting power directly. Go to `bonded` is indeed more friendly to user.

2019-12-03 02:01 UTC, yihuang commented on docs/getting-started/staking.md
> +The rewards validator receives goes directly to the unbonded balance of their staking account.
I think we can change to `bonded`, makes more sense that way.

2019-12-03 02:05 UTC, tomtau commented on docs/getting-started/staking.md
> +The rewards validator receives goes directly to the unbonded balance of their staking account.
Why is unbonded less risky? It seems more risky, because for bonded, one needs to wait a unbonding period before being able to withdraw during which period byzantine faults may be detected -- e.g. one may accumulate rewards in unbonded until there's a lot, launch an attack and withdraw immediately (so only the bonded amount will be slashed rather than the full amount)

2019-12-03 02:07 UTC, tomtau commented on docs/getting-started/staking.md
> +```
is this one correct @lezzokafka ? I thought the decay parameter update may be less frequent than reward distribution period?

2019-12-03 02:19 UTC, tomtau commented on docs/getting-started/staking.md
> +The rewards validator receives goes directly to the unbonded balance of their staking account.
The only thing about changing the voting power is that if the reward distribution period is too frequent (e.g. after every block), it'll be inefficient, as one will keep generating validatorupdates

2019-12-03 02:27 UTC, yihuang commented on docs/getting-started/staking.md
> +```
It seems the `0.95` was for a year period, it needs to be adjusted to a day period, like `0.99986`, but we can't use `Millis` anymore, maybe use some third-party fixed-point number library.

2019-12-03 02:49 UTC, lezzokafka commented on docs/getting-started/staking.md
> +```
@tomtau In this example, *0.95 is the drops per annum.
At the moment it is updated every reward epoch ( sth like 0.95^(1/365) ~0.9986 each day) to provide a "smoother" drops.

If It sounds too frequent, we can make it configurable of how often this decay parameter changes (every $n$ epoch etc.) .

2019-12-04 00:51 UTC, lezzokafka approved these changes

2019-12-04 01:29 UTC, merged