Problem: (CRO-609) Missing chain-docs for validator reward and distribution mechanism
crypto-com/thaler-docs pull request #36
Opened 2019-12-09 08:36 UTC by lezzokafka

Updated
- `getting-started/staking.md`
- `getting-started/transaction.md`
Added
- `getting-started/network-parameters.md`  for future referencing

2019-12-09 08:40 UTC, lezzokafka commented
Remarks:
 The section of transaction fee from `getting-started/staking.md` has been moved to  `getting-started/transaction.md`

2019-12-09 08:46 UTC, devashishdxt approved these changes

2019-12-09 15:36 UTC, yihuang approved these changes

2019-12-10 01:33 UTC, tomtau requested changes
looks ok, not sure if the new pages will be rendered (in html and pdf) if they are not put in the config -- https://github.com/crypto-com/chain-docs/blob/master/docs/.vuepress/config.js#L47
@lezzokafka have you tried rendering the page?

2019-12-10 02:11 UTC, merged

2019-12-10 02:12 UTC, lezzokafka commented
Oppps..!  

Thanks @tomtau  👍