(CRO-325) Problem: chain-docs don't mention cross-currency transfers
crypto-com/thaler-docs pull request #40
Opened 2019-12-19 02:03 UTC by lezzokafka

Solution:
- Added cross-currency transfers interledger demo to `getting-started/transaction.md`;
- Edited and updated `getting-started/consensus.md` with references.

2019-12-20 07:39 UTC, devashishdxt approved these changes

2019-12-20 07:41 UTC, tomtau requested changes
a few changes

2019-12-20 07:41 UTC, tomtau commented on docs/getting-started/consensus.md
> +This interface allows a "plugging" custom applications with Tendermint. Specifically, if the application is written in Go, it can be linked directly wtih the cahin; otherwise, a connection can be est
> wtih the cahin

some typos?

2019-12-20 07:41 UTC, tomtau commented on docs/getting-started/consensus.md
> +For the overall architecture of Tendermint Core consensus engine with the ABCI, please refer to this [infographic](https://github.com/mobfoundry/hackatom/raw/master/tminfo.pdf) and this [guide](https
the diagram is ok... the second link may better point to https://docs.tendermint.com/master/app-dev/app-architecture.html

2019-12-20 07:41 UTC, tomtau commented on docs/getting-started/consensus.md
> +To query a blockchain or submit a transaction, one can use the [Tendermint RPC](https://tendermint.readthedocs.io/en/v0.10.4/rpc.html) for that. Details of this RPC and its mechanism can be found in
for the first link: https://docs.tendermint.com/master/tendermint-core/rpc.html

2019-12-20 07:41 UTC, tomtau commented on docs/getting-started/consensus.md
> +- Root of a Merkle tree of a valid transactions in a given block;
it has another component now -- serialised network parameters

2019-12-20 07:42 UTC, leejw51crypto approved these changes

2019-12-30 01:34 UTC, lezzokafka commented on docs/getting-started/consensus.md
> +- Root of a Merkle tree of a valid transactions in a given block;
Added new component : "Serialised network parameters"👍

2019-12-30 01:35 UTC, lezzokafka commented on docs/getting-started/consensus.md
> +To query a blockchain or submit a transaction, one can use the [Tendermint RPC](https://tendermint.readthedocs.io/en/v0.10.4/rpc.html) for that. Details of this RPC and its mechanism can be found in
Updated with the new link 👍

2019-12-30 01:36 UTC, lezzokafka commented on docs/getting-started/consensus.md
> +This interface allows a "plugging" custom applications with Tendermint. Specifically, if the application is written in Go, it can be linked directly wtih the cahin; otherwise, a connection can be est
Fixed 🤣

2019-12-30 01:36 UTC, lezzokafka commented on docs/getting-started/consensus.md
> +For the overall architecture of Tendermint Core consensus engine with the ABCI, please refer to this [infographic](https://github.com/mobfoundry/hackatom/raw/master/tminfo.pdf) and this [guide](https
Updated with the new link 👍

2019-12-30 02:17 UTC, yihuang commented on docs/getting-started/consensus.md
> +This interface allows a "plugging" custom applications with Tendermint. Specifically, if the application is written in Go, it can be linked directly wtih the chain; otherwise, a connection can be est
```suggestion
This interface allows a "plugging" custom applications with Tendermint. Specifically, if the application is written in Go, it can be linked directly with the chain; otherwise, a connection can be established via 3 TCP or Unix sockets. The details of this interface can be found [here](https://docs.tendermint.com/master/spec/abci/abci.html#overview).
```

2019-12-30 02:44 UTC, lezzokafka commented on docs/getting-started/consensus.md
> +This interface allows a "plugging" custom applications with Tendermint. Specifically, if the application is written in Go, it can be linked directly wtih the chain; otherwise, a connection can be est
thanks @yihuang 🤣

2019-12-30 13:18 UTC, calvinaco approved these changes

2019-12-31 03:06 UTC, merged