(CRO-633) Problem: Chain-docs don't cover voting power
crypto-com/thaler-docs pull request #41
Opened 2019-12-31 01:38 UTC by lezzokafka

Solution: Added _Voting power and proposer selection_  section.

2020-01-02 02:22 UTC, tomtau requested changes
looks ok, just two small suggestions

2020-01-02 02:22 UTC, tomtau commented on docs/getting-started/staking.md
> +The chance of being a proposer is directly proportional to their *voting power* at that time, which, in general, is equal to the `bonded` amount in the associated staking address of the council node.
equal -- perhaps `proportional`? just to clarify that the amounts are in full units / coins, not base units / carsons

2020-01-02 02:22 UTC, tomtau commented on docs/getting-started/staking.md
this is a bit imprecise with regards to that `max_validators` network argument -- it's either minimal stake network parameter or the lowest stake if there are max validators

2020-01-02 02:22 UTC, tomtau commented on docs/getting-started/staking.md
I don't know if that's mentioned elsewhere in the text

2020-01-02 02:22 UTC, tomtau commented on docs/getting-started/staking.md
> +The chance of being a proposer is directly proportional to their *voting power* at that time, which, in general, is equal to the `bonded` amount in the associated staking address of the council node.
or that "amounts" mean full coin amounts could be stated somewhere in the overall text

2020-01-02 03:21 UTC, lezzokafka commented on docs/getting-started/staking.md
> +The chance of being a proposer is directly proportional to their *voting power* at that time, which, in general, is equal to the `bonded` amount in the associated staking address of the council node.
Yes, I thought about this earlier as well, in the case of the node is not being punished,  the voting power will be _"Set to the bonded amount"_ , see [END/COMMIT_BLOCK_STATE_UPDATE](https://crypto-com.github.io/getting-started/staking.html#%E2%80%9Cglobal-state%E2%80%9D-app-hash). Might i ask what's the actual implementation that gives us the voting power?  @devashishdxt

2020-01-02 03:23 UTC, lezzokafka commented on docs/getting-started/staking.md
> +The chance of being a proposer is directly proportional to their *voting power* at that time, which, in general, is equal to the `bonded` amount in the associated staking address of the council node.
btw if it is being scaling up, 
> Voting power uses an int64 but must be positive, thus the range is: 0 through 9223372036854775807. Because of how the current proposer selection algorithm works, we do not recommend having voting powers greater than 10^12 (ie. 1 trillion).

2020-01-02 22:59 UTC, tomtau commented on docs/getting-started/staking.md
> +The chance of being a proposer is directly proportional to their *voting power* at that time, which, in general, is equal to the `bonded` amount in the associated staking address of the council node.
@lezzokafka https://github.com/crypto-com/chain/blob/master/chain-core/src/init/coin.rs#L268

2020-01-03 09:20 UTC, lezzokafka commented on docs/getting-started/staking.md
Cool cool, added the case of maximum validator is reached.

2020-01-06 01:13 UTC, tomtau approved these changes

2020-01-06 01:13 UTC, merged