Problem: outdated getting started docs
crypto-com/thaler-docs pull request #49
Opened 2020-01-13 10:11 UTC by foreseaz

Solutions: update getting started, only include env setup with Azure. Issue [#43]

2020-01-13 10:25 UTC, foreseaz commented
The new getting-started page preview: https://crypto-chain-doc.surge.sh/getting-started/#pre-requisites

2020-01-13 14:17 UTC, lezzokafka commented
Frist PR! @foreseaz

2020-01-14 02:19 UTC, lezzokafka commented on docs/getting-started/README.md
> +If you are the first time to setup a node of Crypto Chain, a warm reminder is that
```suggestion
If you are the first time to setup a node of Crypto.com Chain, a warm reminder is that
```

2020-01-14 02:20 UTC, lezzokafka commented on docs/getting-started/README.md
> +Before diving into details and ~~possibly~~ dependency hell, we would like to introduce you the big picture of Crypto Chain's main components as following:
``` suggestion 
Before diving into details and ~~possibly~~ dependency hell, we would like to introduce you the big picture of Crypto.com Chain's main components as following:
```

2020-01-14 02:21 UTC, lezzokafka commented on docs/getting-started/README.md
> +SSH to the Azure VM, and start the environment setup for Crypto Chain.
``` suggestion
SSH to the Azure VM, and start the environment setup for Crypto.com Chain.
```

2020-01-14 02:32 UTC, lezzokafka commented on docs/getting-started/README.md
> +
Can link to [Chain ID and Network ID](https://crypto-com.github.io/getting-started/chain-id-and-network-id.html#chain-id-and-network-id)

2020-01-14 03:10 UTC, lezzokafka commented
Maybe also hide the SPID in the picture?

2020-01-14 03:25 UTC, foreseaz commented on docs/getting-started/README.md
> +If you are the first time to setup a node of Crypto Chain, a warm reminder is that
Thanks for the review!

2020-01-14 04:21 UTC, tomtau requested changes
left a few comments -- I haven't read through it fully yet, but looks good so far

2020-01-14 04:21 UTC, tomtau commented on docs/getting-started/README.md
> +chains' setup. A special type of hardware is needed and the reference of [SGX-hardware](https://github.com/ayeks/SGX-hardware)
"security concerns" is a bit imprecise -- it's for payment data confidentiality... the relevant doc (transaction-privacy.md / https://crypto-com.github.io/getting-started/transaction-privacy.html#motivation ) could also be linked here

2020-01-14 04:21 UTC, tomtau commented on docs/getting-started/README.md
> +By following this tutorial, you can compile and run Crypto.com chain from scratch.
probably add / highlight *latest version* and *for development*... as it's not necessary for other use cases

2020-01-14 04:21 UTC, tomtau commented on docs/getting-started/README.md
> +The following document will walk you through running a full node on [Azure Confidential Compute VM](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-azure-compute.confidentialc
It's a public website, so I'd avoid this sort of public endorsements without previous approvals -- besides, I'm not even sure if Azure is the most affordable; some time ago, the quoted prices of the other vendors were similar.
The only more affordable one was OVHCloud.

As this is for development only, it's also not necessary / recommended to use cloud -- the best is your own machine if possible :) 

So instead of "we do recommend".... I'd rephrase it as something like "If your development machine does not support SGX, we recommend spinning up a cloud instance. In this guide, we will walk through the process of setting it up on Azure."

2020-01-14 04:21 UTC, tomtau commented on docs/getting-started/README.md
> +it may take you one hour or two to fully setup and run the Chain. But, `DON'T PANIC` we will
"fully setup a development environment"

2020-01-14 04:56 UTC, foreseaz commented on docs/getting-started/README.md
> +chains' setup. A special type of hardware is needed and the reference of [SGX-hardware](https://github.com/ayeks/SGX-hardware)
Great! That's exactly the reviews and feedbacks I am looking for. Please provide more technical background, motivations, how we make the decisions, etc.
I will update this part.

2020-01-14 04:57 UTC, foreseaz commented on docs/getting-started/README.md
> +The following document will walk you through running a full node on [Azure Confidential Compute VM](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/microsoft-azure-compute.confidentialc
I see, I will update it.

2020-01-14 05:04 UTC, foreseaz commented on docs/getting-started/README.md
> +
We can actually add a `Glossary ` page to define all the terms and variables we used.

2020-01-14 07:02 UTC, lezzokafka commented on docs/getting-started/README.md
> +
Cool cool, I have listed some [network parameters](https://crypto-com.github.io/getting-started/network-parameters.html) here, we can gather some terms and variables to form a list later.

2020-01-14 07:08 UTC, tomtau requested changes
looks all right, but the environment setup could be simplified -- I only compiled Intel SDK/PSW once when I needed to compile it with extra debugging support due to some problems in AESM I tried to diagnose... but that's more of a system developer concern.

This guide should be a general developer guide, and there's no need for such depth

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +![](./assets/big_pic.png)
the picture is ok, but the arrows are a little bit confusing -- for example, chain-abci doesn't connect to tx-query app wrapper, it only advertises the connection string (ip/hostname:port) for the client

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +- Install `Docker`: you can refer to following document [How To Install and Use Docker on Ubuntu 18.04
once you have a Docker, the quickest getting started is just `docker pull cryptocom/chain:latest` (this image has Rust at that needed version, libzmq and Intel SDK) and working inside that container -- you just need to expose it the device or the AESM socket -- see https://github.com/apache/incubator-teaclave-sgx-sdk/wiki/Environment-Setup#docker-setup

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +## Setup SGX Environment
if this guide shows how to do with Azure + Docker, then this isn't necessary.

(and the recommended way would be to grab released binaries from https://01.org/intel-software-guard-extensions/downloads instead of building them from scratch)

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +to sign up for the ID and KEY. It won't take you more than 5 mins.
perhaps clarify this is for IAS in staging / development environment

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +$ RUST_LOG=debug ./tx-query-app  0.0.0.0:3443 tcp://127.0.0.1:25933
if using a Docker, some care may be needed (for exposing / mapping the ports).

if not using a Docker, I think it's easier to use `ipc://....` zeroMQ socket on a local machine for inter-process communication

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +$ cargo build --release
no need to build with `--release` for development

2020-01-14 07:08 UTC, tomtau commented on docs/getting-started/README.md
> +$ unzip ./tendermint_v0.32.1_linux_amd64.zip
I recommend using the latest released version (0.32.9)

2020-01-14 08:48 UTC, lezzokafka commented on docs/getting-started/README.md
> +Make sure what your subscription is [DEV Intel® Software Guard Extensions Attestation Service (Unlinkable)](https://api.portal.trustedservices.intel.com/Products/dev-intel-software-guard-extensions-a
Login required for the link

2020-01-15 08:02 UTC, foreseaz commented on docs/getting-started/README.md
> +- Install `Docker`: you can refer to following document [How To Install and Use Docker on Ubuntu 18.04
So using this docker, I can omit the part of `## Setup SGX Environment`?

2020-01-15 08:32 UTC, calvinaco requested changes

2020-01-15 08:32 UTC, calvinaco commented on docs/getting-started/README.md
> +You should get follow result:
```suggestion
You should get the following result:
```

2020-01-15 08:32 UTC, calvinaco commented on docs/getting-started/README.md
> +export SPID=YOUR_SPID
I suggest to give more visual hint of change needed
```suggestion
export SPID={YOUR_SPID}
```

2020-01-15 08:32 UTC, calvinaco commented on docs/getting-started/README.md
> +export IAS_API_KEY=YOUR_PRIMARY_KEY
```suggestion
export IAS_API_KEY={YOUR_PRIMARY_KEY}
```

2020-01-15 08:32 UTC, calvinaco commented on docs/getting-started/README.md
> +[INFO  tx_query_app] [+] Init Query Enclave Successful 2!
Just curious, is the "Successful *_2_*!" suppose to be a debug message?

2020-01-15 08:32 UTC, calvinaco commented on docs/getting-started/README.md
> +After successfully complied, you will get the following binary files in `./target/release` folder:
Following Tomas comment, If you don' use `--release`, update here to `./target/debug` as well.

2020-01-15 09:01 UTC, tomtau commented on docs/getting-started/README.md
> +- Install `Docker`: you can refer to following document [How To Install and Use Docker on Ubuntu 18.04
Yes, pretty much -- on a normal machine, you'd just need to do Step 0 (installing the driver): https://github.com/apache/incubator-teaclave-sgx-sdk/wiki/Environment-Setup#intel-sgx-toolchain-setup if on Azure with OpenEnclave ticked, then it's already installed

2020-01-15 09:04 UTC, tomtau commented on docs/getting-started/README.md
> +[INFO  tx_query_app] [+] Init Query Enclave Successful 2!
yes perhaps, Linfeng added logging, but it may need some log level tweaking not to make it too chatty

2020-01-16 11:03 UTC, foreseaz commented
Thanks for all the reviews and comments! I just followed through Linfeng's makefile flow and it's really well-organized. I will update a new getting started according to the `make` flow. For the current PR, I will try to extract some parts out as in-depth manual building reference.

2020-01-20 02:20 UTC, foreseaz commented
Preview at https://crypto-chain-doc.surge.sh/getting-started/  for new make flow

2020-01-20 02:24 UTC, tomtau approved these changes
👍the getting started guide is much simpler with that makefile

2020-01-20 02:26 UTC, merged

2020-01-20 02:30 UTC, foreseaz commented
Exactly! Thanks @linfeng-crypto 's efforts!