Problem: update outdated `send your first tx` docs
crypto-com/thaler-docs pull request #56
Opened 2020-01-21 10:12 UTC by foreseaz

Preview here https://crypto-chain-doc.surge.sh/getting-started/send_your_first_transaction.html

2020-01-21 10:15 UTC, foreseaz commented
Encountered some problems involving running with Docker. Recorded here:
[#950](https://github.com/crypto-com/chain/issues/950)
[#951](https://github.com/crypto-com/chain/issues/951)

2020-01-22 06:14 UTC, tomtau commented
@foreseaz I opened this issue: https://github.com/crypto-com/chain/issues/960

2020-01-22 07:01 UTC, tomtau requested changes
left a few comments -- cli may have some changes in UX

2020-01-22 07:01 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +From the getting started section, we have already kicked off the Crypto.com Chain with the
I think the original section @lezzokafka wrote was trying to explain this as a general concept -- so it could be someone as a developer who went through the "getting started" setup, or it could be someone trying the public testnet (where there "genesis fund" note isn't relevant -- so it was perhaps leaned more towards "getting started" developers).

It's fine to have it more linked / geared towards a developer -- if that's done, I think:

1. it should have some warning note saying that the reader is a developer and went through the getting started.

2. there should be an equivalent version/section for the released public testnet version -- e.g. in 0.2 binaries, it should still be +- up to date ... or perhaps this is adequate: https://crypto-com.github.io/wallets/client-cli.html#wallet-storage ?

2020-01-22 07:01 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Congradulations! You successfully withdraw all the unbonded genesis fund and now can transfer to others.
```suggestion
Congratulations! You successfully withdraw all the unbonded genesis fund and now can transfer to others.
```

2020-01-22 07:01 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
That's not correct -- only `TransferTx`, `DepositStakeTx` and `WithdrawUnbondedTx` have some of their payloads obfuscated.
(It's not correct here though: https://crypto-com.github.io/getting-started/transaction.html#transaction-types  ...  all data in `UnbondStakeTx` is open to everyone)

Could also link to: https://crypto-com.github.io/getting-started/transaction-privacy.html#motivation

Anyway, the general intuition is here: https://crypto-com.github.io/getting-started/transaction-accounting-model.html#motivation

- staking operations need maximal transparency
- payments need some payment data confidentiality

`TransferTx` is for payments, so almost all of its data is obfuscated... `DepositStakeTx` and `WithdrawUnbondedTx` are for moving in or out of the "staking world", so a part of their data are fully visible, a part of their data are obfuscated

2020-01-22 07:01 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
view-key is mainly for workflows where the sender can't push directly data to the receiver.

it's also possible to send/receive a payment by directly exchanging the (raw) transaction payload data -- the sender (who creates the transaction) would export it, the receiver would import it and check the transaction data locally (and check the transaction ID against the distributed ledger).

It may interesting / useful to also show this "flow". @linfeng-crypto added these commands before: https://github.com/crypto-com/chain/pull/695

2020-01-22 07:01 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +If you are interested in contribution or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
as mentioned in the other comment -- if this is for developers, then it doesn't correspond to how to "send the first transaction" on the testnet... so perhaps it should be split / there could be a separate page showing these workflows, but assuming one uses the released binary (rather than building the latest code from master) and obtained the funds from the faucet (instead of setting it at genesis)

2020-01-23 02:09 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +From the getting started section, we have already kicked off the Crypto.com Chain with the
Sure! the general concept of sending first tx makes more sense! I am now haven't tried sending tx on testnet. I will add the warning first and update for the testnet part in the future!

2020-01-23 02:11 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
Great background info! I will look into that!

2020-01-23 02:13 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +If you are interested in contribution or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
Sure thing! I will think about what's a better flow to present these two use cases.

2020-01-23 02:19 UTC, lezzokafka reviewed
I see your plan, once you set up a node and get the blockchain running with the default devent setting; 
the next step is to allow developers to recover the wallet ( from the default seed which has funds in it) and interact with the blockchain by sending a transaction.

2020-01-23 02:19 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> -```
I think this transaction flow should be kept in somewhere, as it is mentioned  in some other sections:
for example the [Transaction types](https://crypto-com.github.io/getting-started/transaction.html#transaction-types)

2020-01-23 07:01 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
> (It's not correct here though: https://crypto-com.github.io/getting-started/transaction.html#transaction-types ... all data in `UnbondStakeTx` is open to everyone)

Fixed in #59, no worries 💃

2020-02-24 07:49 UTC, tomtau reviewed
@foreseaz @lezzokafka what is the plan about this PR?

2020-02-26 07:44 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +From the getting started section, we have already kicked off the Crypto.com Chain with the
Updates, yes, I think the https://crypto-com.github.io/wallets/client-cli.html#funds-transfer is enough for the user and this page could be the continuation of `getting started`, I have already added the caution.

2020-02-27 03:11 UTC, calvinaco commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
After this section is updated I think I am good to approve this PR

2020-02-27 03:12 UTC, calvinaco commented on docs/getting-started/send_your_first_transaction.md
> +If you are interested in contribution or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
Agree, I think the problem of current chain doc is it is mixed with Devnet setup and Testnet setup. So perhaps we should have separate section on Devnet and Testnet. This could also corelate to the target-audience-role-oriented design we discussed before.

2020-02-27 03:14 UTC, calvinaco commented on docs/getting-started/send_your_first_transaction.md
> -```
I think it is now the `./assets/states.png` shown at the beginning of this page

2020-02-27 03:15 UTC, calvinaco commented on docs/getting-started/send_your_first_transaction.md
> -```
I think it is now the ./assets/states.png shown at the beginning of this page

2020-02-27 03:15 UTC, calvinaco requested changes

2020-02-27 03:15 UTC, calvinaco commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
After this section is updated I think I am good to approve this PR

2020-02-27 04:01 UTC, lezzokafka commented
> @foreseaz @lezzokafka what is the plan about this PR?

@foreseaz  is finishing the last import/export tx bit, will be updated soon.

2020-02-27 04:05 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> -```
Oh cool, I found [it](https://user-images.githubusercontent.com/51898510/75411172-4b639400-5959-11ea-9047-fcc09e0dafb1.png).

2020-02-27 04:21 UTC, lezzokafka commented
> > @foreseaz @lezzokafka what is the plan about this PR?
> 
> @foreseaz is finishing the last import/export tx bit, will be updated soon.

I break it and raised a new issue #92, so that @foreseaz  can finish this PR first.

2020-02-27 04:53 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +If you are interested in contribution or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
Already updated

2020-02-27 04:54 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +Only people with those view keys can decrypt transaction data and view raw transaction.
Due to my local cli env problems, I left the export & import tx commands for @lezzokafka to finish #92

2020-02-27 04:56 UTC, foreseaz commented
Updated & pls review~ Due to my local cli env problems, I left the export & import tx commands for @lezzokafka to finish #92 Thanks.

2020-02-27 09:15 UTC, lezzokafka requested changes
Looking good, left some suggested changes / comments 👍

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Then you will get the `Authentication token`, remember the token and it will be needed for all authorised commands.
```suggestion
Then you will get the `Authentication token`, keep the token safe and it will be needed for all authorised commands.
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +$ /target/debug/client-cli state --address 0x2dfde2178daa679508828242119dcf2114038ea8 --name Default
```suggestion
$ /target/debug/client-cli state --address 0x2dfde2178daa679508828242119dcf2114038ea8
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Enter authentication token: b74ce4590ebc9d3c2a3adace926304384ae9451f43560c9702402be53811da8b
```suggestion

```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +- Besides, you can check the bond status of the wallet by the following command:
Maybe put this after creating the staking address in "## Create Transfer & Staking Address"?

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +simple make commands and docker. However, there is multiple [tendermint configs](https://github.com/crypto-com/chain/tree/master/docker/config/devnet/tendermint) should be explained.
```suggestion
simple make commands and docker. However, there are multiple [tendermint configs](https://github.com/crypto-com/chain/tree/master/docker/config/devnet/tendermint) should be explained.
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +- Create Transfer address, which is a UTXO address, of `Bob` wallet:
Not sure should we call it a UTXO address here, any thought @calvinaco ?

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Check the `balance`:
You might want to emphasis `balance` is only for **_transferable_** balance, which does not include the _bonded/unbonded_ amount of staking addresses under the wallet.

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +As mentioned before, sender should add the receiver's view-key to the transaction. Because sender can't push data directly to the receiver. However, it is also possible to send / receive a payment by
```suggestion
As mentioned before, sender should add the receiver's view-key to the transaction. Because sender can't push data directly to the receiver. However, it is also possible to send / receive a payment by directly exchanging the (raw) transaction payload data. The sender (who creates the transaction) would export it, the receiver would import it and check the transaction data locally and check the transaction ID against the distributed ledger. Following explains the flow:
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +- Get your transaction id from the history, you may need to sync before run following command:
```suggestion
- Get your transaction id from the history, you may need to sync before running the following command:
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +If you are interested in contribution or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
```suggestion
If you are interested in contributing or joining our testnet, you can continue reading the following sections about `Running a Full Node to join Thaler Testnet` and `Local Full Node Development`.
```

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +$ /target/debug/client-cli state --address 0x2dfde2178daa679508828242119dcf2114038ea8 --name Default
Updated in  [#1035](https://github.com/crypto-com/chain/pull/1035)

2020-02-27 09:15 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Enter authentication token: b74ce4590ebc9d3c2a3adace926304384ae9451f43560c9702402be53811da8b
Same as above

2020-02-27 09:18 UTC, calvinlauco commented on docs/getting-started/send_your_first_transaction.md
> +- Create Transfer address, which is a UTXO address, of `Bob` wallet:
How is UTXO address coined? I think transfer address is good enough?

2020-03-05 04:03 UTC, foreseaz commented on docs/getting-started/send_your_first_transaction.md
> +- Create Transfer address, which is a UTXO address, of `Bob` wallet:
Transfer addresss then!

2020-03-05 04:27 UTC, lezzokafka approved these changes

2020-03-05 04:34 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +- Besides, you can check the bond status of the wallet by the following command:
Resolved

2020-03-05 08:01 UTC, calvinlauyh approved these changes

2020-03-06 02:20 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Sender could associate one or more `view-keys` onto the transactions. The view-key associated wallet could easily sync and view the transaction.
or zero views keys

2020-03-06 02:20 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Sender could associate one or more `view-keys` onto the transactions. The view-key associated wallet could easily sync and view the transaction.
but that may be more advanced for "first transaction" tutorial

2020-03-06 02:24 UTC, tomtau requested changes
looks all right, just the ending is unfinished -- so perhaps there should be a todo note?

2020-03-06 02:24 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Then, you can verify the transaction by ...
I guess this is "TODO"?

2020-03-06 02:24 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Sender could associate one or more `view-keys` onto the transactions. The view-key associated wallet could easily sync and view the transaction.
(and the current implementation of client-cli includes the sender view key by default anyway)

2020-03-06 02:24 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Then, you can verify the transaction by ...
one would verify it if one can use its output at the moment?

2020-03-06 02:26 UTC, lezzokafka commented on docs/getting-started/send_your_first_transaction.md
> +Then, you can verify the transaction by ...
Will pick it up with #92

2020-03-06 02:46 UTC, tomtau commented on docs/getting-started/send_your_first_transaction.md
> +Then, you can verify the transaction by ...
ok, so I'll just merge this one as it is

2020-03-06 02:46 UTC, merged