Problem: No specification for validator logic.
crypto-com/thaler-docs pull request #75
Opened 2020-02-05 17:52 UTC by yihuang

Solution:
- Write a specification with pseudo-sql codes.

2020-02-06 08:40 UTC, tomtau commented on docs/getting-started/validator-spec.md
> +#### Handle deposit/unbond tx
what about `unbond` and interaction with the minimal required stake network parameter?

2020-02-06 08:57 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +#### Handle deposit/unbond tx
That is handled in `end_block` when computing validator updates for tendermint.

2020-02-06 09:00 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +#### Handle deposit/unbond tx
Oh, sorry, I think I deleted an important line of code, I'll add it back = ="

2020-02-09 09:06 UTC, yihuang commented
https://github.com/yihuang/chain/blob/validator-spec/chain-core/src/state/validator_spec.rs
A rust implementation for this spec.

2020-02-12 06:12 UTC, tomtau commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
@devashishdxt I'm not sure about these constraints.
isn't enough `unbonding_period >= jail_duration`, `jail_duration >= max_evidence_age` and `jail_duration >= slash_wait_period`?

The purpose of jail / unbond time should correspond to the "max evidence duration" in Tendermint consensus parameters (as a standard nothing-at-stake mitigation).
The purpose of `slash_wait_period` was, if I'm not mistaken, to have a "grace" period during which only the worst detected infraction is punished.

2020-02-12 06:29 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
`slash_wait_period >= max_evidence_age` is to make sure all the faults being detected before execute slashing.
Regarding `unbonding_period >= max_evidence_age + slash_wait_period`, it is unneeded, 
because withdrawing is forbidden after validator gets jailed, I didn't take that into consideration.

2020-02-12 06:32 UTC, devashishdxt commented on docs/getting-started/validator-spec.md
> +- `jail_duration`
Should we add unit of measurement at the end of each config? For example, `jail_duration_secs`, etc.

2020-02-12 06:32 UTC, devashishdxt commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
`slash_wait_period` should be greater than `max_evidence_age`. I think following three conditions should be enough (`jail_duration >= max_evidence_age` here is implied).
- `unbonding_period >= jail_duration`
- `jail_duration >= slash_wait_period`
- `slash_wait_period >= max_evidence_age`

2020-02-12 06:32 UTC, devashishdxt commented on docs/getting-started/validator-spec.md
> +- Table is implemented with `Slab<Row>`, unique index/primary key is implemented as `BTreeMap<field, usize>` or `HashMap<field, usize>`, non-unique index is implemented as `BTreeMap<field, Vec<usize>
Are we planning to use these generic table data structures (`Slab<Row>`) in code? If yes, why not directly use concrete `struct` for that table?

2020-02-12 06:34 UTC, tomtau commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
> is to make sure all the faults being detected before execute slashing.

 "all faults" during which period?

2020-02-12 06:43 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
> > is to make sure all the faults being detected before execute slashing.
> 
> "all faults" during which period?

The period of `max_evidence_age` before the first fault detected. It is possible for the faults to be detected out of order?

2020-02-12 06:45 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +- `jail_duration`
> Should we add unit of measurement at the end of each config? For example, `jail_duration_secs`, etc.

I agree, but currently the spec is more like a prototype, to see if it makes sense. There are even cases it works differently from the current implementation.

2020-02-12 06:51 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +- Table is implemented with `Slab<Row>`, unique index/primary key is implemented as `BTreeMap<field, usize>` or `HashMap<field, usize>`, non-unique index is implemented as `BTreeMap<field, Vec<usize>
> Are we planning to use these generic table data structures (`Slab<Row>`) in code? If yes, why not directly use concrete `struct` for that table?

I try to make the spec as simple as possible, I just happen to find relational DB language seems simplest here.
For a table, there are well-established concepts like index/join/order/filter, which takes extra rust code to implement.

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +  liveness_tracker [bool; block_signing_window] null,
Is there a tracker to indicate the block time when this node becomes active? 
It is a part of ` council_node_info`?

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
Once a validator being jailed, Its voting power should go zero; which means it can not misbehave in the consensus process any more. Then the `slash_wait_period` starts ticking, wait for evidence (if any) and see if there are any even worst misbehaviour.

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
> `slash_wait_period >= max_evidence_age` is to make sure all the faults being detected before execute slashing.

I agree with this ^

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
`slash_wait_period`
                                <----------------------->
                 (           ) |                         | 
                  <--------->  ^                         ^
                  `max_e_age`  Jail                     Slash

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
The period is ` max_evidence_age` before the _Jail_  point

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
@yihuang Faults could be detected out of order. The actual case should be something like:  
A validator got charged and jailed due to a lower penalty fault (say liveness) and but we will still open to any other evidence for  `slash_wait_period` and see if it also commit double sign fault. 

(the other way round is trivial due to we have already charge it with the higher one)

The logic to me is, change it first, if you see anything, which also "lockdown" the funds. Then we give it plenty of time to see if we need to penalize it even further.

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `jail_duration`
Haha, of course. That is chain [#874](https://github.com/crypto-com/chain/issues/874)

2020-02-12 07:25 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +  staking_address text primary key,
Should be some consensus-related metadata like `validator_address`

2020-02-12 14:13 UTC, lezzokafka commented on docs/getting-started/validator-spec.md
> +- `unbonding_period >= max_evidence_age + slash_wait_period`
` jail_duration`
                               <--------------------------------->

              (     ...    )   ║                         ¦       ║

              <----...---->    ^                         ^       ^
                  `max_e_age`  |                         |       |
                             Jailing                   Slash   Able to unjaill      
                                         
                                <----------------------->
                                   `slash_wait_period`

2020-02-12 14:32 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +  liveness_tracker [bool; block_signing_window] null,
AFAIK, currently no such info.

2020-02-12 14:33 UTC, yihuang commented on docs/getting-started/validator-spec.md
> +  staking_address text primary key,
> Should be some consensus-related metadata like `validator_address`

Fixed, good catch.

2020-02-27 02:27 UTC, devashishdxt requested changes
This now diverges a lot from https://github.com/crypto-com/chain-docs/pull/89. Can you either remove punishemts from this or modify them based on the punishement specifications PR?

2020-02-27 02:33 UTC, yihuang commented
> This now diverges a lot from #89. Can you either remove punishemts from this or modify them based on the punishement specifications PR?

Maybe we can close this, and re-do it based on new rules.

2020-02-27 02:33 UTC, closed without merging