Problem: no explanation of reward configuration parameters
crypto-com/thaler-docs pull request #90
Opened 2020-02-20 08:51 UTC by lezzokafka

Solution: 
Rewrote the section  "Validator Rewards": 
- The first part (overview) come with easy examples with graphs and for the layman, 
- Then we go more in-depth with the actual calculation and explain what's the network parameters with examples in the monetary expansion section.

- Took away the "Punishments" as it is now a separated one under #89

2020-02-20 09:11 UTC, devashishdxt commented on docs/getting-started/staking.md
> +To virtualize this, if we set `tau=10 Billion`, `R0=350`, we have the following graph of the function:
virtualize?

2020-02-20 09:17 UTC, lezzokafka commented on docs/getting-started/staking.md
> +To virtualize this, if we set `tau=10 Billion`, `R0=350`, we have the following graph of the function:
Opps, visualize is what I mean

2020-02-21 03:22 UTC, devashishdxt commented on docs/getting-started/staking.md
> +    P = rewards_config["distribution_period:"]
```suggestion
    P = rewards_config["distribution_period"]
```

2020-02-21 03:22 UTC, devashishdxt commented on docs/getting-started/staking.md
> +    S = total_staking  # example: 1500000000_00000000
Can you specify how this `total_staking` value is calculated for a rewards period?

2020-02-21 03:22 UTC, tomtau requested changes
examples are good -- it'll be all good to explain how setting individual parameters higher or lower will affect the emission.

2020-02-21 03:22 UTC, tomtau commented on docs/getting-started/staking.md
> +where `S` is the total amount of tokens staked by validators to participate in the consensus process; `R0` is the upper bound for the reward rate; `tau` is a time-dependent variable that controls the
"exceptional rate" -> "exponential rate"?

2020-02-24 02:12 UTC, lezzokafka commented on docs/getting-started/staking.md
> +where `S` is the total amount of tokens staked by validators to participate in the consensus process; `R0` is the upper bound for the reward rate; `tau` is a time-dependent variable that controls the
Nice catch! Thanks Tomas

2020-02-24 02:15 UTC, lezzokafka commented on docs/getting-started/staking.md
> +where `S` is the total amount of tokens staked by validators to participate in the consensus process; `R0` is the upper bound for the reward rate; `tau` is a time-dependent variable that controls the
> examples are good -- it'll be all good to explain how setting individual parameters higher or lower will affect the emission.

Sure, I plan to put this in the next PR when resolving #80.

2020-02-24 02:26 UTC, lezzokafka commented on docs/getting-started/staking.md
> +    S = total_staking  # example: 1500000000_00000000
@devashishdxt  I change it to a description rather then a number here: 

    # total bonded amount of the active validators 
    at the end of the reward epoch
    S = total_staking

2020-02-24 02:26 UTC, lezzokafka commented on docs/getting-started/staking.md
> +    P = rewards_config["distribution_period:"]
Thanks :)

2020-02-24 07:39 UTC, merged