LivenessTracker should be updated in EndBlock
crypto-com/thaler-docs pull request #97
Opened 2020-03-03 02:48 UTC by devashishdxt

Changes:

- `LivenessTracker` should be updated in `EndBlock`. Reason: If we do not update `LivenessTracker` in `EndBlock`, we'll have to put update statements in all the places where a validator's voting power changes to zero (jailing, unbonding, etc.). On the other hand, if we update `LivenessTracker` in `EndBlock` based on `power_changed_in_block`, we won't have to worry about updating liveness tracker in different places.
- Added instruction to add a new validator to `LivenessTracker` when they join the network as a validator using `NodeJoinTx`.
- Fixed some typos.

2020-03-03 03:20 UTC, tomtau commented on docs/getting-started/punishments.md
> +  obtained from `power_changed_in_block`).
`power_changed_in_block` is undefined -- some WIP of how this can be retrieved was described in: https://github.com/crypto-com/chain-docs/pull/75/files

2020-03-04 02:12 UTC, devashishdxt commented on docs/getting-started/punishments.md
> +  obtained from `power_changed_in_block`).
Added an overview of how validator changes work in code and also explained `power_changed_in_block`. Please check.

2020-03-04 02:58 UTC, tomtau commented on docs/getting-started/punishments.md
> +So, setting voting power in `power_changed_in_block` to zero means that those validators will be removed.
Not necessarily -- e.g. in one block
"unbondtx (some amount) -> sets power to 0"
"deposit (other amount) -> sets power back up"

depending on the amount, and other actions in that block, one can't simply tell what will happen in end block.

`power_changed_in_block` was just this temporary internal helper that's been regretfully misused and shouldn't be relied on as some sort of universal validator update semantics (that's not defined anywhere).
Punishments may require setting more things than just that.
--

The only important part here is what happens with regards to ABCI -- which is that at end block, it should generate a ValidatorUpdate for the node's associated consensus pub key and set the vote power to 0.

2020-03-04 03:04 UTC, tomtau requested changes
the note is a bit misleading.
what should be there is perhaps blocked by: https://github.com/crypto-com/chain-docs/issues/81 ?

2020-03-04 03:29 UTC, devashishdxt commented
> the note is a bit misleading.
> what should be there is perhaps blocked by: #81 ?

I agree with you. Modified the PR (removed all the mentions of `power_changed_in_block`).

2020-03-04 04:05 UTC, merged